import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
process.on('uncaughtException',error=>{console.error(error.message,error.where||'');process.exit(1);});
const {PGlite}=await import(pathToFileURL(process.argv[2]).href);
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table profiles(id uuid primary key,full_name text,email_verified_at timestamptz default now());
create table organizations(id uuid primary key,owner_id uuid references profiles(id),verified boolean default false);
create table organization_members(organization_id uuid,user_id uuid,role text);
create table job_postings(id uuid primary key,title text,status text,closes_at timestamptz);
create table opportunities(id uuid primary key,title text,status text,deadline timestamptz);
alter table opportunities enable row level security;
grant select on opportunities to anon,authenticated;
create function public.is_admin_or_mod() returns boolean language sql as $$select false$$;
revoke execute on function public.is_admin_or_mod() from public,anon;
grant execute on function public.is_admin_or_mod() to authenticated;
create policy "Active and closed opportunities are viewable by everyone" on opportunities for select using(status in ('active','closed') or public.is_admin_or_mod());
create function public.require_verified_member_write() returns trigger language plpgsql security definer set search_path='' as $$begin if auth.uid() is not null and not exists(select 1 from public.profiles where id=auth.uid() and email_verified_at is not null) then raise exception 'Verify your email before using this feature.' using errcode='42501'; end if;return new;end$$;
create table notifications(id uuid primary key default gen_random_uuid(),user_id uuid,type text,title text,message text,link text,actor_id uuid,actor_name text,created_at timestamptz default now());
create table reports(id uuid primary key default gen_random_uuid(),reporter_id uuid,reason text,post_id uuid,opportunity_id uuid, constraint reports_exactly_one_target check(num_nonnulls(post_id,opportunity_id)=1));
create function social_notifications_enabled(uuid) returns boolean language sql as $$select true$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
grant usage on schema storage to authenticated;grant select,insert,delete on storage.objects to authenticated;`);
await db.exec(fs.readFileSync('supabase/migrations/20260928184352_possara_groups_help.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260929073350_community_verified_writes.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260929075942_community_opportunities_organizations.sql','utf8'));
const owner='00000000-0000-4000-8000-000000000001',member='00000000-0000-4000-8000-000000000002',outsider='00000000-0000-4000-8000-000000000003';
await db.query('insert into profiles(id,full_name) values($1,$2),($3,$4),($5,$6)',[owner,'Owner',member,'Member',outsider,'Outsider']);
const org='00000000-0000-4000-8000-000000000020',job='00000000-0000-4000-8000-000000000021',expired='00000000-0000-4000-8000-000000000022';
await db.query('insert into organizations(id,owner_id) values($1,$2)',[org,owner]);
await db.query("insert into job_postings values($1,'Designer','open',now()+interval '1 day'),($2,'Expired designer','open',now()-interval '1 day')",[job,expired]);
async function as(uid){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role authenticated');}
async function action(name,gid=null,payload={}){return (await db.query('select public.community_action($1,$2,$3) as result',[name,gid,payload])).rows[0].result;}
async function denied(fn,regex){await assert.rejects(fn,regex);}
await as(owner);
const pub=(await action('create',null,{name:'Public group',privacy:'public'})).id;
const official=(await action('create',null,{name:'Official organization group',privacy:'private',organization_id:org})).id;
assert.equal((await db.query('select organization_id from community_groups where id=$1',[official])).rows[0].organization_id,org);
await action('share_opportunity',pub,{kind:'job',target_id:job,note:'A useful opening'});
await denied(()=>action('share_opportunity',pub,{kind:'job',target_id:job}),/already shared/);
await denied(()=>action('share_opportunity',pub,{kind:'job',target_id:expired}),/no longer open/);
const priv=(await action('create',null,{name:'Private group',privacy:'private',approval_required:true})).id;
const token=(await action('invite',priv)).token;
const request=(await action('send',pub,{kind:'request',body:'Help with a portfolio'})).id;
assert.equal((await action('send',pub,{client_message_id:request,kind:'request',body:'Retry after a lost response'})).id,request);
assert.equal((await db.query('select * from community_messages')).rows.length,1);
await as(outsider);
await denied(()=>action('create',null,{name:'Fake official group',organization_id:org}),/organization manager/);
await denied(()=>action('share_opportunity',pub,{kind:'job',target_id:job}),/membership/);
assert.equal((await db.query('select * from community_opportunities')).rows.length,0);
assert.equal((await db.query('select * from community_groups')).rows.length,1);
assert.equal((await db.query('select * from community_messages')).rows.length,0);
await denied(()=>action('send',pub,{body:'Intruder'}),/membership/);
await denied(()=>db.query('insert into community_members(group_id,user_id,role) values($1,$2,$3)',[pub,outsider,'owner']),/permission denied/);
await denied(()=>action('join',priv),/invitation/);
await denied(()=>action('settings',pub,{approval_required:false}),/membership/);
await as(member);
await action('join',pub);await action('join_invite',null,{token});
const shared=(await db.query('select * from community_opportunities')).rows[0];
assert.equal(shared.job_id,job);
await denied(()=>action('remove_opportunity',pub,{id:shared.id}),/cannot remove/);
assert.equal((await db.query('select * from community_messages')).rows.length,1);
await denied(()=>action('send',priv,{body:'Pending member'}),/membership/);
await denied(()=>action('promote',pub,{user_id:member}),/admins/);
await denied(()=>action('resolve',pub,{message_id:request}),/cannot change/);
await action('react',pub,{message_id:request,reaction:'thanks'});
assert.equal((await db.query('select * from community_reactions')).rows.length,1);
await action('react',pub,{message_id:request,reaction:'thanks'});
assert.equal((await db.query('select * from community_reactions')).rows.length,0);
await action('report',pub,{message_id:request,reason:'Testing report moderation'});
await action('preferences',pub,{muted:true});
await as(owner);await action('approve',priv,{user_id:member});await action('resolve',pub,{message_id:request});
await action('rotate_invite',priv);
await as(outsider);await denied(()=>action('join_invite',null,{token}),/no longer/);
await as(member);
const path=`${priv}/${member}/attachment`;
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['community-files',path]);
const attachment=(await action('send',priv,{body:'Shared guide',file_path:path,file_name:'guide.pdf'})).id;
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await as(outsider);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await denied(()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['community-files',`${priv}/${outsider}/intruder`]),/row-level security/);
await as(owner);
await db.exec('reset role');await db.exec("update community_messages set created_at=now()-interval '1 minute'");await db.exec('set role authenticated');
await denied(()=>action('send',pub,{body:'Cross group reply',reply_to_id:attachment}),/foreign key/);
await action('send',pub,{body:'Muted member should not receive notification'});
await denied(()=>action('leave',priv),/owner/);
await action('remove',priv,{user_id:member});
await as(member);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await denied(()=>action('send',priv,{body:'Removed member'}),/membership/);
await action('leave',pub);assert.equal((await db.query('select * from community_messages')).rows.length,0);
await db.exec('reset role');
await db.query('update profiles set email_verified_at=null where id=$1',[outsider]);
await as(outsider);await denied(()=>action('create',null,{name:'Unverified group'}),/Verify your email/);
await db.exec('reset role');
assert.equal((await db.query('select * from reports')).rows.length,1);
assert.equal((await db.query("select * from notifications where user_id=$1 and link like $2",[member,`/groups/${pub}%`])).rows.length,0);
assert.equal((await db.query("select * from notifications where user_id=$1 and link=$2",[owner,`/groups/${priv}?message=${attachment}`])).rows.length,1);
await db.exec('set role anon');await denied(()=>action('create',null,{name:'Anonymous group'}),/permission denied/);
await db.query('select * from opportunities');
console.log('PASS: groups creation, public/private discovery, membership approval, role escalation denial, reactions, help resolution, reports, invitations, attachment RLS, cross-group reply denial, removal, mute and exact notification routing.');
await db.close();
