import assert from 'node:assert/strict';
import { chooseNextStep, deadlineCalendar } from '../src/lib/nextStep.ts';
const now = Date.parse('2026-09-28T12:00:00Z');
const item = (id, days, status = 'active') => ({ id, title: id, path: '/opportunities/' + id, status, deadline: days === null ? null : new Date(now + days * 86400000).toISOString() });
assert.equal(chooseNextStep([item('later', 5), item('soon', 1)], [item('match', 4)], now).opportunity.id, 'soon');
assert.equal(chooseNextStep([item('expired', -1), item('closed', 1, 'closed')], [item('match', 4)], now).reason, 'match');
assert.equal(chooseNextStep([item('saved', null)], [], now).reason, 'saved');
assert.equal(chooseNextStep([item('expired', 0)], [], now), null);
assert.equal(chooseNextStep([], [item('closed', 1, 'closed')], now), null);
const opportunity = { ...item('calendar', 2), title: 'Scholarship, research; ' + '🌍'.repeat(50) + '\r\nBEGIN:VEVENT' };
const calendar = deadlineCalendar(opportunity, 'https://possara.pages.dev', now);
assert.ok(calendar.includes('DTSTART:20260930T120000Z'));
assert.ok(calendar.includes('TRIGGER:-P1D'));
assert.ok(calendar.includes('URL:https://possara.pages.dev/opportunities/calendar'));
assert.equal(calendar.split('\r\n').filter(line => line === 'BEGIN:VEVENT').length, 1);
for (const line of calendar.split('\r\n')) assert.ok(Buffer.byteLength(line, 'utf8') <= 75);
assert.ok(calendar.replace(/\r\n /g, '').includes('Scholarship\\, research\\;'));
assert.ok(!deadlineCalendar(item('soon', 0.5), 'https://possara.pages.dev', now).includes('VALARM'));
assert.throws(() => deadlineCalendar(item('expired', -1), 'https://possara.pages.dev', now));
assert.throws(() => deadlineCalendar({ ...opportunity, path: '//evil.example' }, 'https://possara.pages.dev', now));
console.log('PASS: deadline priority, valid matches, expired/closed filtering, calendar UTC time, text escaping, Unicode folding, safe links and reminder timing.');
