export type UserRole="user"|"creator"|"moderator"|"admin";
export type EducationLevel="secondary"|"undergraduate"|"graduate"|"postgraduate"|"not_in_school";
export type OpportunityStatus="active"|"closed"|"draft"|"flagged";
export type OpportunitySource="user_submitted"|"ai_suggested"|"partner_direct"|"automated_discovery";

export type Profile={id:string;full_name:string|null;avatar_url:string|null;bio:string|null;location:string|null;website:string|null;instagram_url:string|null;x_url:string|null;tiktok_url:string|null;linkedin_url:string|null;youtube_url:string|null;facebook_url:string|null;country:string|null;currency:string|null;language:string|null;timezone:string|null;last_seen_at:string|null;created_at:string;education_level:EducationLevel|null;skills:string[];goal_categories:string[];username:string|null;headline:string|null;profession:string|null;workplace:string|null;school:string|null;cover_url:string|null;interests:string[];preferred_opportunity_countries:string[];remote_opportunities:boolean;opportunity_discoverable:boolean;onboarding_completed:boolean;birthday_month:number|null;birthday_day:number|null;birthday_visibility:"everyone"|"followers"|"private"};
export type UserRoleRow={user_id:string;role:UserRole;is_verified:boolean;is_banned:boolean;ban_reason:string|null;banned_at:string|null;updated_at:string|null};
export type Organization={id:string;owner_id:string|null;name:string;slug:string;logo_url:string|null;website:string|null;verified:boolean|null;is_sponsored:boolean|null;local_verification_source:string|null;description:string|null;created_at:string;industry:string|null;country:string|null;state:string|null;headquarters:string|null};
export type OpportunityCategory={id:string;name:string;slug:string;description:string|null;icon:string|null;color:string|null};
export type Opportunity={id:string;author_id:string|null;organization_id:string|null;category_id:string|null;title:string;description:string;eligibility:string|null;deadline:string|null;location:string|null;link:string|null;tags:string[]|null;status:OpportunityStatus|null;source:OpportunitySource;last_verified_at:string|null;discovery_candidate_id:string|null;search_vector:string|null;created_at:string;updated_at:string};
export type Post={id:string;author_id:string|null;type:"general"|"opportunity"|"resource"|"event"|null;content:string;media_urls:string[]|null;topic:string|null;visibility:string|null;status:"published"|"removed"|null;deleted_at:string|null;category_id:string|null;shared_from_post_id:string|null;search_vector:string|null;created_at:string};
export type Comment={id:string;post_id:string|null;author_id:string|null;parent_id:string|null;content:string;deleted_at:string|null;created_at:string};
export type Advertisement={id:string;submitted_by:string|null;organization_name:string;title:string;description:string;link:string;image_url:string|null;status:"pending"|"active"|"rejected"|null;created_at:string;amount_paid:number|null;currency:string|null;payment_reference:string|null};
export type Story={id:string;author_id:string;media_url:string|null;storage_path:string|null;audience:"public"|"followers";caption:string|null;story_type:"image"|"text";text_body:string|null;background_style:"midnight"|"plum"|"sunset"|"ocean"|"emerald"|"gold";music_path:string|null;music_mime_type:string|null;music_title:string|null;created_at:string;expires_at:string};
export type MemberStats={total_members:number;online_now:number};
export type PlatformStats={active_opportunities:number;verified_organizations:number;opportunities_saved:number;community_posts:number;sparks_given:number;countries_represented:number};
export type Database=any;
