import { useRef, useState } from "react";
import { Megaphone } from "lucide-react";
import { useActiveAdvertisements, useSubmitAdvertisement } from "../hooks/useAdvertisements";
import { useAuth } from "../store/auth";

function AdCard({ ad }: { ad: { organization_name: string; title: string; description: string; link: string; image_url: string | null } }) {
  return <a href={ad.link} target="_blank" rel="noreferrer" className="block rounded-2xl border border-paper-dim bg-white shadow-sm p-4 transition hover:border-opportunity hover:shadow-md">{ad.image_url && <img src={ad.image_url} alt="" className="mb-3 h-32 w-full rounded-lg object-cover" />}<span className="text-xs font-medium uppercase tracking-wide text-opportunity-dark">Sponsored · {ad.organization_name}</span><h3 className="mt-0.5 text-[15px] font-medium leading-snug">{ad.title}</h3><p className="mt-1 line-clamp-2 text-sm text-ink-light">{ad.description}</p></a>;
}
function SubmitAdForm() {
  const { userId } = useAuth(); const submitAd = useSubmitAdvertisement(); const fileInputRef = useRef<HTMLInputElement>(null);
  const [organizationName, setOrganizationName] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [link, setLink] = useState(""); const [imageFile, setImageFile] = useState<File | null>(null); const [success, setSuccess] = useState(false); const [error, setError] = useState<string | null>(null);
  if (!userId) return <p className="text-ink-light">Sign in to create an advertisement.</p>;
  if (success) return <div className="rounded-xl border border-trust-light bg-trust-light/40 p-5"><p className="text-trust-dark">Submitted for review. Payment activation will be added during the Paystack staging phase; submitting this form does not activate the ad.</p></div>;
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); setError(null); try { await submitAd.mutateAsync({ organizationName, title, description, link, imageFile }); setSuccess(true); } catch (err) { setError((err as Error).message); } }
  return <form onSubmit={handleSubmit} className="space-y-4 rounded-2xl border border-paper-dim bg-white shadow-sm p-5"><div><label className="mb-1 block text-sm text-ink-light" htmlFor="org-name">Business or organization name</label><input id="org-name" required value={organizationName} onChange={(e)=>setOrganizationName(e.target.value)} className="w-full rounded-lg border border-ink-faint/30 px-3 py-2 outline-none focus:border-trust"/></div><div><label className="mb-1 block text-sm text-ink-light" htmlFor="ad-title">Ad title</label><input id="ad-title" required value={title} onChange={(e)=>setTitle(e.target.value)} className="w-full rounded-lg border border-ink-faint/30 px-3 py-2 outline-none focus:border-trust"/></div><div><label className="mb-1 block text-sm text-ink-light" htmlFor="ad-description">Description</label><textarea id="ad-description" required rows={3} value={description} onChange={(e)=>setDescription(e.target.value)} className="w-full rounded-lg border border-ink-faint/30 px-3 py-2 outline-none focus:border-trust"/></div><div><label className="mb-1 block text-sm text-ink-light" htmlFor="ad-link">Destination link</label><input id="ad-link" type="url" required placeholder="https://…" value={link} onChange={(e)=>setLink(e.target.value)} className="w-full rounded-lg border border-ink-faint/30 px-3 py-2 outline-none focus:border-trust"/></div><div><label className="mb-1 block text-sm text-ink-light" htmlFor="ad-image">Image</label><input id="ad-image" ref={fileInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>setImageFile(e.target.files?.[0] ?? null)} className="text-sm"/></div>{error&&<p className="text-sm text-flag">{error}</p>}<button type="submit" disabled={submitAd.isPending} className="rounded-full bg-ink px-5 py-2 text-sm font-medium text-paper hover:bg-ink/90 disabled:opacity-50">{submitAd.isPending?"Submitting…":"Submit for review"}</button></form>;
}
export function Advertise() { const { data: ads, isLoading } = useActiveAdvertisements(); const [showForm,setShowForm]=useState(false); return <div><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl">Advertise</h1><p className="mt-1 max-w-prose text-ink-light">Create a clear, image-led campaign for eligible public POSSARA feeds. Every active campaign is labelled Sponsored.</p></div><button onClick={()=>setShowForm(v=>!v)} className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-full border border-ink-faint/30 px-4 py-2 text-sm font-medium hover:border-ink"><Megaphone size={15}/>{showForm?"Hide form":"Create ad"}</button></div>{showForm&&<div className="mt-5 max-w-lg"><SubmitAdForm/></div>}<div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{isLoading&&<div className="animate-pulse rounded-2xl border border-paper-dim bg-white shadow-sm p-4"><div className="h-4 w-2/3 rounded bg-paper-dim"/><div className="mt-2 h-3 w-full rounded bg-paper-dim"/></div>}{!isLoading&&ads?.length===0&&<p className="col-span-full text-ink-light">No active sponsored campaigns right now.</p>}{ads?.map((ad)=><AdCard key={ad.id} ad={ad}/>)}</div></div>; }
