import { GroupSearch } from "../components/GroupSearch";
import { GroupOpportunities } from "../components/GroupOpportunities";
import { OrganizationVerificationBadge } from "../components/OrganizationVerificationBadge";
import { useMyOrganizations } from "../hooks/useHiring";
import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowLeft, Bell, BellOff, Check, Download, HandHeart, Lock, MessageCircle, Paperclip, Pin, Plus, Send, Users, X } from "lucide-react";
import { useGroups, useGroup, useGroupAction, uploadGroupFile, downloadGroupFile, GROUP_FILE_ACCEPT, type GroupMessage, type GroupReaction } from "../hooks/useGroups";
import { usePersistentDraft } from "../hooks/usePersistentDraft";
import { useAuth } from "../store/auth";
import { supabase } from "../lib/supabase";

const button="inline-flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50";
const secondary="inline-flex items-center justify-center gap-2 rounded-xl border border-paper-dim bg-white px-3 py-2 text-sm font-medium disabled:opacity-50";
const input="w-full rounded-xl border border-paper-dim bg-white p-3 text-sm outline-none focus:border-brand";
const errorText=(error:unknown)=>error instanceof Error?error.message:typeof error==="object"&&error&&"message" in error?String(error.message):"Something went wrong. Please try again.";

export function Groups(){
 const {userId}=useAuth();const query=useGroups();const action=useGroupAction();const navigate=useNavigate();const [params]=useSearchParams();
 const {data:myOrganizations}=useMyOrganizations();
 const [search,setSearch]=useState("");const [creating,setCreating]=useState(params.get("create")==="1");const [error,setError]=useState("");
 const [draft,setDraft,clearDraft,storageError]=usePersistentDraft(`group-create:${userId}:${params.get("organization")??"personal"}`,{name:"",description:"",privacy:"public",approval_required:false,rules:"",organization_id:params.get("organization")??""});
 const [invite,setInvite]=useState(params.get("invite")??"");
 async function joinInvite(){try{setError("");const token=invite.trim().split("invite=").pop()?.split("&")[0];if(!token||!/^[a-f0-9-]{36}$/i.test(token))throw new Error("Paste a valid group invitation link.");const result=await action.mutateAsync({action:"join_invite",payload:{token}});navigate(`/groups/${result.id}`);}catch(e){setError(errorText(e));}}
 return <div className="page-stack max-w-4xl">
  <Link to="/connect" className="inline-flex items-center gap-2 text-sm text-ink-light"><ArrowLeft size={16}/>Connect</Link>
  <section className="rounded-3xl bg-gradient-to-br from-brand-light via-white to-trust-light p-6"><p className="eyebrow">A place to belong</p><h1 className="mt-2 text-3xl">POSSARA Groups</h1><p className="mt-2 max-w-xl text-ink-light">Find your people. Ask for help, share what you know, and move forward together.</p><button className={`${button} mt-5`} onClick={()=>setCreating(!creating)}><Plus size={18}/>Create a group</button></section>
  {(error||storageError)&&<p role="alert" className="text-sm text-red-600">{error||storageError}</p>}
  {creating&&<form className="space-y-3 rounded-2xl border border-paper-dim bg-white p-5" onSubmit={async e=>{e.preventDefault();try{setError("");const result=await action.mutateAsync({action:"create",payload:draft});clearDraft();navigate(`/groups/${result.id}`);}catch(err){setError(errorText(err));}}}>
   <h2 className="text-lg">Start something useful</h2>
   {!!myOrganizations?.length&&<label className="block text-sm">Create for<select className={`${input} mt-1`} value={draft.organization_id??""} onChange={e=>setDraft({...draft,organization_id:e.target.value})}><option value="">My community</option>{myOrganizations.map((row:any)=><option key={row.organizations.id} value={row.organizations.id}>{row.organizations.name} - official group</option>)}</select></label>}
   <label className="block text-sm">Group name<input className={`${input} mt-1`} required minLength={2} maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
   <label className="block text-sm">What is this group for?<textarea className={`${input} mt-1`} maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
   <label className="block text-sm">Privacy<select className={`${input} mt-1`} value={draft.privacy} onChange={e=>setDraft({...draft,privacy:e.target.value})}><option value="public">Public — anyone on POSSARA can find and join</option><option value="private">Private — invitation required</option></select></label>
   <p className="text-xs text-ink-light">Only members can read conversations and download files in either type of group.</p>
   <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.approval_required} onChange={e=>setDraft({...draft,approval_required:e.target.checked})}/>Require admin approval to join</label>
   <label className="block text-sm">Group rules<textarea className={`${input} mt-1`} maxLength={2000} value={draft.rules} onChange={e=>setDraft({...draft,rules:e.target.value})} placeholder="Be kind. Respect privacy. No spam."/></label>
   <button className={button} disabled={action.isPending}>Create group</button>
  </form>}
  <div className="flex flex-wrap gap-2"><input className={`${input} min-w-0 flex-1`} aria-label="Invitation link" placeholder="Have an invitation? Paste the link" value={invite} onChange={e=>setInvite(e.target.value)}/><button className={secondary} disabled={!invite.trim()||action.isPending} onClick={joinInvite}>Join by invite</button></div>
  <input className={input} aria-label="Search groups" placeholder="Search groups by name or purpose" value={search} onChange={e=>setSearch(e.target.value)}/>
  {query.isPending&&<p role="status">Loading groups…</p>}{query.error&&<p role="alert">Could not load groups. <button onClick={()=>query.refetch()} className="underline">Try again</button></p>}
  <div className="grid gap-3 sm:grid-cols-2">{query.data?.groups.filter(g=>(!params.get("organization")||g.organization_id===params.get("organization"))).filter(g=>`${g.name} ${g.description}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(query.data.members.some(m=>m.group_id===b.id))-Number(query.data.members.some(m=>m.group_id===a.id))).map(g=>{const membership=query.data.members.find(m=>m.group_id===g.id);return <Link key={g.id} to={`/groups/${g.id}`} className="min-w-0 rounded-2xl border border-paper-dim bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><span className="rounded-xl bg-brand-light p-3 text-brand-dark"><Users size={22}/></span><span className="text-xs text-ink-light">{membership?.status==='active'?'Joined':membership?.status==='pending'?'Awaiting approval':g.privacy==='private'?'Private':'Public'}</span></div><h2 className="break-words text-lg">{g.name}{membership?.status==='active'&&g.last_message_at&&g.last_message_at>membership.last_read_at&&<span className="ml-2 inline-block rounded-full bg-brand px-2 py-0.5 align-middle text-[10px] text-white">New</span>}</h2><p className="mt-1 line-clamp-2 break-words text-sm text-ink-light">{g.description||'Conversation, help and shared possibilities.'}</p>{g.organization&&<p className="mt-3 flex items-center gap-1 text-xs text-brand-dark">{g.organization.name}{g.organization.verified&&<OrganizationVerificationBadge compact/>}</p>}</Link>;})}</div>
  {query.data?.groups.length===0&&<p className="rounded-2xl border border-dashed p-6 text-center text-ink-light">Your community can start here. Create the first group or join through an invitation.</p>}
 </div>;
}

export function GroupPage(){
 const {id}=useParams();const [params]=useSearchParams();return <GroupContent key={`${id}:${params.get("message")??""}`} id={id}/>;
}
function GroupContent({id}:{id:string|undefined}){
 const {userId}=useAuth();const [params]=useSearchParams();const targetId=params.get("message");const query=useGroup(id,targetId);const action=useGroupAction();const navigate=useNavigate();
 const [tab,setTab]=useState<'chat'|'help'|'files'|'members'|'opportunities'>('chat');const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [file,setFile]=useState<File|null>(null);const [fileKey,setFileKey]=useState(0);const [reply,setReply]=useState<GroupMessage|null>(null);
 const [draft,setDraft,clearDraft,storageError]=usePersistentDraft<{body:string;kind:string;client_message_id?:string}>(`group-message:${userId}:${id}`,{body:"",kind:"chat"});
 const [older,setOlder]=useState<GroupMessage[]>([]);const [olderReactions,setOlderReactions]=useState<GroupReaction[]>([]);const [historyEnd,setHistoryEnd]=useState(false);const [historyBusy,setHistoryBusy]=useState(false);
 const targetScrolled=useRef<string|null>(null);
 const data=query.data;const membership=data?.members.find(m=>m.user_id===userId);const active=membership?.status==='active';const managing=active&&membership.role!=='member';
 const latestMessage=data?.messages.at(-1)?.id;
 useEffect(()=>{if(!active||!id)return;const mark=()=>{if(document.visibilityState==='visible')void supabase.rpc('community_action',{action:'preferences',gid:id,payload:{read:true}}).then(({error})=>{if(error)console.warn('Could not update group read status');});};mark();document.addEventListener('visibilitychange',mark);return()=>document.removeEventListener('visibilitychange',mark);},[active,id,latestMessage]);
 useEffect(()=>{if(!targetId||!data||targetScrolled.current===targetId)return;const element=document.getElementById('message-'+targetId);if(element){element.scrollIntoView({block:'center',behavior:'smooth'});targetScrolled.current=targetId;}},[targetId,data]);
 async function loadOlder(){const cursor=older[0]??data?.oldest;if(!cursor||!id)return;setHistoryBusy(true);try{const result=await supabase.from('community_messages').select('*').eq('group_id',id).or('created_at.lt.'+cursor.created_at+',and(created_at.eq.'+cursor.created_at+',id.lt.'+cursor.id+')').order('created_at',{ascending:false}).order('id',{ascending:false}).limit(100);if(result.error)throw result.error;const rows=result.data as GroupMessage[];const reactionResult=rows.length?await supabase.from('community_reactions').select('*').in('message_id',rows.map(m=>m.id)):{data:[],error:null};if(reactionResult.error)throw reactionResult.error;setOlder(old=>[...rows.reverse(),...old]);setOlderReactions(old=>[...old,...reactionResult.data as GroupReaction[]]);setHistoryEnd(rows.length<100);}catch(e){setError(errorText(e));}finally{setHistoryBusy(false);}}
 async function run(name:string,payload:Record<string,unknown>={}){setError("");setNotice("");try{const result=await action.mutateAsync({action:name,gid:id,payload});if(payload.message_id&&older.some(m=>m.id===payload.message_id)){const [messageResult,reactionResult]=await Promise.all([supabase.from('community_messages').select('*').eq('id',String(payload.message_id)).eq('group_id',id!).maybeSingle(),supabase.from('community_reactions').select('*').eq('message_id',String(payload.message_id))]);if(messageResult.error)throw messageResult.error;if(reactionResult.error)throw reactionResult.error;if(messageResult.data)setOlder(previous=>previous.map(m=>m.id===payload.message_id?messageResult.data as GroupMessage:m));setOlderReactions(previous=>[...previous.filter(r=>r.message_id!==payload.message_id),...reactionResult.data as GroupReaction[]]);}return result;}catch(e){setError(errorText(e));return null;}}
 async function send(){
  if(!id||!userId||busy)return;
  setBusy(true);setError("");let path:string|undefined;
  const clientId=draft.client_message_id??crypto.randomUUID();
  setDraft({...draft,client_message_id:clientId});
  try{
   if(file)path=await uploadGroupFile(id,userId,file);
   const result=await action.mutateAsync({action:'send',gid:id,payload:{...draft,client_message_id:clientId,kind:reply?'chat':draft.kind,reply_to_id:reply?.id??null,...(path?{file_path:path,file_name:file!.name}:{})}});
   if(path&&result.file_path!==undefined&&result.file_path!==path)await supabase.storage.from('community-files').remove([path]);
   clearDraft();setFile(null);setFileKey(k=>k+1);setReply(null);setNotice("Sent");
  }catch(e){
   // A lost response may follow a committed send. Only remove uploads when the
   // server explicitly rejected the transaction; retries reuse the message ID.
   if(path&&typeof e==='object'&&e&&'code' in e&&/^(P0001|23)/.test(String(e.code)))await supabase.storage.from('community-files').remove([path]);
   setError(errorText(e));
  }finally{setBusy(false);}
 }
 if(query.isPending)return <p role="status">Loading group…</p>;
 if(query.error)return <p role="alert">Could not load this group. <button onClick={()=>query.refetch()} className="underline">Try again</button></p>;
 if(!data)return <div className="page-stack"><h1>Group unavailable</h1><p>This group may be private. Use an invitation from a group admin.</p><Link to="/groups">Browse groups</Link></div>;
 const {group,members}=data;
 const messages=[...new Map([...older,...data.messages].map(m=>[m.id,m])).values()].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));
 const reactions=[...new Map([...olderReactions,...data.reactions].map(r=>[r.message_id+":"+r.user_id,r])).values()];
 const displayName=(authorId:string)=>members.find(m=>m.user_id===authorId)?.profile?.full_name||members.find(m=>m.user_id===authorId)?.profile?.username||'Member';
 const visible=messages.filter(m=>tab==='help'?m.kind!=='chat':tab==='files'?!!m.file_path:true);
 return <div className="page-stack mx-auto max-w-3xl pb-6">
  <Link to="/groups" className="inline-flex items-center gap-2 text-sm text-ink-light"><ArrowLeft size={16}/>Groups</Link>
  <header className="rounded-2xl border border-brand/10 bg-gradient-to-br from-brand-light to-white p-5"><div className="flex items-start gap-3"><span className="rounded-xl bg-white p-3 text-brand-dark"><Users size={24}/></span><div className="min-w-0 flex-1"><h1 className="break-words text-2xl">{group.name}</h1><p className="mt-1 flex items-center gap-1 text-xs text-ink-light">{group.privacy==='private'&&<Lock size={12}/>} {group.privacy==='private'?'Private':'Public'} group{active&&` · ${members.filter(m=>m.status==='active').length} members`}</p></div>{active&&<button className={secondary} title={membership.muted?'Unmute group':'Mute group'} aria-label={membership.muted?'Unmute group':'Mute group'} disabled={action.isPending} onClick={()=>run('preferences',{muted:!membership.muted})}>{membership.muted?<BellOff size={18}/>:<Bell size={18}/>}</button>}</div><p className="mt-3 whitespace-pre-wrap break-words text-sm text-ink-light">{group.description}</p>{group.organization&&<Link to={`/organizations/${group.organization.slug}`} className="mt-3 flex items-center gap-2 text-xs font-medium text-brand-dark">Official group of {group.organization.name}{(group.organization.verified||group.organization.verification_status==='verified')&&<OrganizationVerificationBadge compact/>}</Link>}{group.rules&&<details className="mt-3 text-sm"><summary className="cursor-pointer font-medium">Group rules</summary><p className="mt-2 whitespace-pre-wrap break-words">{group.rules}</p></details>}</header>
  {(error||storageError)&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error||storageError}</p>}{notice&&<p role="status" className="break-all text-sm text-brand-dark">{notice}</p>}
  {!active?<div className="rounded-2xl border bg-white p-5"><p className="mb-3 text-sm">{membership?.status==='pending'?'Your request is waiting for an admin to approve it.':membership?.status==='banned'?'You cannot join this group.':'Join to take part in conversations, share files, and help each other.'}</p>{!membership&&group.privacy==='public'&&<button className={button} disabled={action.isPending} onClick={()=>run('join')}>{group.approval_required?'Request to join':'Join group'}</button>}</div>:<>
   <GroupSearch groupId={id!}/>
   <nav aria-label="Group sections" className="flex gap-1 overflow-x-auto rounded-2xl bg-white p-1">{([{key:'chat',label:'Chat',Icon:MessageCircle},{key:'help',label:'Help',Icon:HandHeart},{key:'files',label:'Files',Icon:Paperclip},{key:'opportunities',label:'Opportunities',Icon:Plus},{key:'members',label:'Members',Icon:Users}] as const).map(({key,label,Icon})=><button key={key} className={`flex shrink-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-xl px-3 py-3 text-sm ${tab===key?'bg-ink text-white':'text-ink-light'}`} onClick={()=>{setTab(key);if(key==='chat')void run('preferences',{read:true});}}><Icon size={16}/>{label}</button>)}</nav>
   {tab==='opportunities'?<GroupOpportunities groupId={id!} managing={!!managing}/>:tab==='members'?<div className="space-y-4 rounded-2xl border bg-white p-4">
    {managing&&<div className="flex flex-wrap gap-2"><button className={secondary} onClick={async()=>{const result=await run('invite');if(result?.token){const link=`${location.origin}/groups?invite=${result.token}`;try{await navigator.clipboard.writeText(link);setNotice('Invitation link copied.');}catch{setNotice(link);}}}}>Copy invitation link</button><button className={secondary} onClick={async()=>{if(window.confirm('Replace the invitation link? The old link will stop working.')){const result=await run('rotate_invite');if(result)setNotice('Old invitation revoked. Copy the new link to share it.');}}}>Reset invitation</button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={group.approval_required} onChange={e=>run('settings',{approval_required:e.target.checked})}/>Approve new members</label></div>}
    {members.filter(m=>m.status!=='banned').map(m=><div key={m.user_id} className="flex flex-wrap items-center gap-2 border-b border-paper-dim pb-3"><Link className="min-w-0 flex-1 break-words font-medium hover:underline" to={`/profile/id/${m.user_id}`}>{displayName(m.user_id)}<span className="ml-2 text-xs font-normal text-ink-light">{m.status==='pending'?'Awaiting approval':m.role}</span></Link>{managing&&m.user_id!==group.owner_id&&m.user_id!==userId&&<div className="flex flex-wrap gap-2">{m.status==='pending'&&<button className={secondary} disabled={action.isPending} onClick={()=>run('approve',{user_id:m.user_id})}>Approve</button>}{membership.role==='owner'&&m.role==='member'&&m.status==='active'&&<button className={secondary} disabled={action.isPending} onClick={()=>run('promote',{user_id:m.user_id})}>Make admin</button>}<button className={secondary} disabled={action.isPending} onClick={()=>{if(window.confirm(`Remove ${displayName(m.user_id)} and prevent rejoining?`))void run('remove',{user_id:m.user_id});}}>Remove</button></div>}</div>)}
    {membership.role!=='owner'&&<button className="text-sm text-red-600" onClick={async()=>{if(window.confirm('Leave this group?')){const result=await run('leave');if(result)navigate('/groups');}}}>Leave group</button>}
   </div>:<>
    {tab==='help'&&<div className="rounded-2xl bg-trust-light p-4"><h2 className="font-semibold">A little help can change a lot</h2><p className="mt-1 text-sm text-ink-light">Ask for advice, a study partner or practical support. Offer a skill or some time. Mark it resolved when you are done.</p><div className="mt-3 flex flex-wrap gap-2"><button className={secondary} onClick={()=>{setDraft({...draft,kind:'request'});setReply(null);document.getElementById('group-compose')?.focus();}}>I need help</button><button className={secondary} onClick={()=>{setDraft({...draft,kind:'offer'});setReply(null);document.getElementById('group-compose')?.focus();}}>I can help</button></div></div>}
    {!historyEnd&&data.hasOlder&&<button className={secondary} disabled={historyBusy} onClick={loadOlder}>{historyBusy?'Loading earlier activity...':'Load earlier activity'}</button>}
    {targetId&&!messages.some(m=>m.id===targetId)&&<p role="status" className="text-sm text-ink-light">This message is no longer available.</p>}
    {tab==='chat'&&messages.some(m=>m.pinned)&&<div className="flex flex-wrap gap-2 rounded-xl bg-brand-light p-3">{messages.filter(m=>m.pinned).map(m=><button key={m.id} className="max-w-full truncate text-sm text-brand-dark" onClick={()=>document.getElementById('message-'+m.id)?.scrollIntoView({block:'center',behavior:'smooth'})}><Pin size={12} className="mr-1 inline"/>{m.body||m.file_name}</button>)}</div>}
    <div className="space-y-3">{visible.length===0&&<p className="rounded-2xl border border-dashed p-6 text-center text-sm text-ink-light">{tab==='files'?'Shared files will appear here.':tab==='help'?'Be the first to ask for help or offer something useful.':'Start the conversation. Say hello to your group.'}</p>}{visible.map(message=><article id={`message-${message.id}`} key={message.id} className={`min-w-0 scroll-mt-24 rounded-2xl border p-4 ${targetId===message.id?"ring-2 ring-brand ":""}${message.author_id===userId?'border-brand/15 bg-brand-light/25':'border-paper-dim bg-white'}`}>
     <div className="flex items-start gap-2"><Link to={`/profile/id/${message.author_id}`} className="min-w-0 flex-1 break-words text-sm font-semibold hover:underline">{displayName(message.author_id)}</Link><time className="shrink-0 text-[10px] text-ink-light" dateTime={message.created_at}>{new Date(message.created_at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time>{message.pinned&&<Pin size={14} className="shrink-0 text-brand-dark"/>}</div>
     {message.kind!=='chat'&&<p className="mt-2 inline-flex items-center gap-1 rounded-full bg-white px-2 py-1 text-xs font-medium text-brand-dark">{message.resolved?<><Check size={12}/>Resolved</>:message.kind==='request'?'I need help':'I can help'}</p>}
     {message.reply_to_id&&<button className="mt-2 block w-full truncate rounded-lg border-l-2 border-brand bg-white/60 p-2 text-left text-xs text-ink-light" onClick={()=>{setTab('chat');targetScrolled.current=null;navigate(`/groups/${id}?message=${message.reply_to_id}`);}}>Replying to: {messages.find(m=>m.id===message.reply_to_id)?.body||'Earlier message'}</button>}
     <p className="mt-2 whitespace-pre-wrap break-words text-sm [overflow-wrap:anywhere]">{message.body}</p>
     {message.file_path&&<button className={`${secondary} mt-3 max-w-full`} onClick={async()=>{try{await downloadGroupFile(message.file_path!,message.file_name||'attachment');}catch(e){setError(errorText(e));}}}><Download size={16} className="shrink-0"/><span className="truncate">{message.file_name||'Download attachment'}</span></button>}
     <div className="mt-3 flex flex-wrap items-center gap-2">{(['love','thanks','support'] as const).map((reaction,i)=>{const items=reactions.filter(r=>r.message_id===message.id&&r.reaction===reaction);return <button key={reaction} aria-label={`${reaction} reaction, ${items.length}`} aria-pressed={items.some(r=>r.user_id===userId)} className={`rounded-full border px-2 py-1 text-xs ${items.some(r=>r.user_id===userId)?'border-brand bg-brand-light':'border-paper-dim bg-white'}`} disabled={action.isPending} onClick={()=>run('react',{message_id:message.id,reaction})}>{['❤️','🙏','🤝'][i]} {items.length||''}</button>;})}<button className="px-2 py-1 text-xs text-brand-dark" onClick={()=>{setReply(message);document.getElementById('group-compose')?.focus();}}>Reply</button>
      <details className="relative ml-auto text-xs"><summary className="cursor-pointer px-2 py-1">More</summary><div className="absolute right-0 z-10 grid w-44 gap-1 rounded-xl border bg-white p-2 shadow-lg">{(message.author_id===userId||managing)&&message.kind!=='chat'&&<button className="p-2 text-left" onClick={()=>run('resolve',{message_id:message.id})}>{message.resolved?'Reopen':'Mark resolved'}</button>}{managing&&<button className="p-2 text-left" onClick={()=>run('pin',{message_id:message.id})}>{message.pinned?'Unpin':'Pin message'}</button>}{(message.author_id===userId||managing)&&<button className="p-2 text-left" onClick={()=>{if(window.confirm('Remove this message?'))void run('delete',{message_id:message.id});}}>Remove message</button>}<button className="p-2 text-left" onClick={async()=>{const reason=window.prompt('What is wrong with this message?');if(reason){const result=await run('report',{message_id:message.id,reason});if(result)setNotice('Report sent to POSSARA admins.');}}}>Report</button></div></details>
     </div>
    </article>)}</div>
    <form className="space-y-3 rounded-2xl border border-paper-dim bg-white p-4 shadow-sm" onSubmit={e=>{e.preventDefault();void send();}}>
     {reply&&<div className="flex items-center gap-2 rounded-lg bg-brand-light p-2 text-xs"><span className="min-w-0 flex-1 truncate">Replying to {displayName(reply.author_id)}: {reply.body}</span><button type="button" aria-label="Cancel reply" onClick={()=>setReply(null)}><X size={16}/></button></div>}
     <label className="block text-xs font-medium">{reply?'Reply': 'Share with the group'}{!reply&&<select className={`${input} mt-1`} value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}><option value="chat">Message</option><option value="request">I need help</option><option value="offer">I can help</option></select>}</label>
     <textarea id="group-compose" aria-label="Group message" className={input} rows={3} maxLength={6000} placeholder={draft.kind==='request'?'What would help you move forward?':draft.kind==='offer'?'What can you help someone with?':'Write a message…'} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} disabled={busy}/>
     <div className="flex flex-wrap items-center justify-between gap-3"><label className={`${secondary} cursor-pointer`}><Paperclip size={16}/>Attach file<input key={fileKey} className="sr-only" type="file" accept={GROUP_FILE_ACCEPT} disabled={busy} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button className={button} disabled={busy||action.isPending||(!draft.body.trim()&&!file)}><Send size={16}/>{busy?'Sending…':'Send'}</button></div>{file&&<p className="break-all text-xs">{file.name} <button type="button" className="underline" onClick={()=>{setFile(null);setFileKey(k=>k+1);}}>Remove</button></p>}<p className="text-xs text-ink-light">Text drafts survive a refresh. Attachments up to 10 MB; reselect files after refreshing.</p>
    </form>
   </>}
  </>}
 </div>;
}
