import { usePersistentDraft } from "../hooks/usePersistentDraft";
import { useAuth } from "../store/auth";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { CheckCircle2, Clock3, Plus, Trash2 } from "lucide-react";
import { useHiringJob, useRecruiterCbtQuestions, useSaveCbtQuestions, useUpdateJob } from "../hooks/useHiring";
type Draft={questionText:string;choices:string[];correctChoice:string};
const blank=():Draft=>({questionText:"",choices:["","","",""],correctChoice:""});
export function JobCbtBuilder(){
 const {id}=useParams();const {userId}=useAuth();const [validationError,setValidationError]=useState("");const [saved,setSaved]=useState(false);const jobQuery=useHiringJob(id);const {data:job}=jobQuery;const questionsQuery=useRecruiterCbtQuestions(id);const {data:existing,isLoading}=questionsQuery;const save=useSaveCbtQuestions(id||"");const update=useUpdateJob(id||"",job?.organization_id||"");
 const [draft,setDraft,clearDraft,draftError]=usePersistentDraft(userId&&id?`possara-cbt-builder:${userId}:${id}`:null,{rows:existing?.length?existing.map((q:any)=>({questionText:q.question_text,choices:q.choices,correctChoice:q.correct_choice||""})):[blank()],minutes:Math.max(1,Math.round((job?.cbt_time_limit_seconds||900)/60))});
 const rows=draft.rows as Draft[];const minutes=draft.minutes;
 const setRows=(rows:Draft[])=>{setSaved(false);setDraft(prev=>({...prev,rows}));};
 const setMinutes=(minutes:number)=>{setSaved(false);setDraft(prev=>({...prev,minutes}));};
 function patch(i:number,next:Partial<Draft>){setRows(rows.map((r,n)=>n===i?{...r,...next}:r))}
 async function submit(e:React.FormEvent){e.preventDefault();setValidationError("");const clean=rows.map(r=>({...r,questionText:r.questionText.trim(),choices:r.choices.map(x=>x.trim()).filter(Boolean),correctChoice:r.correctChoice.trim()}));if(!clean.length||clean.some(r=>!r.questionText||r.choices.length<2||new Set(r.choices).size!==r.choices.length||!r.choices.includes(r.correctChoice))){setValidationError("Complete every question, use distinct choices and select its correct answer.");return;}try{await save.mutateAsync({rows:clean,timeLimitSeconds:Math.max(60,Math.min(10800,Math.round(minutes*60)))});clearDraft();setSaved(true);}catch{/* Mutation error is shown below. */}}
 if(jobQuery.isLoading||isLoading)return <p role="status">Loading assessment setup...</p>;
 if(jobQuery.error||questionsQuery.error)return <div className="empty-state"><h1>Assessment setup could not load</h1><p role="alert">{(jobQuery.error||questionsQuery.error)?.message}</p><button onClick={()=>{void jobQuery.refetch();void questionsQuery.refetch();}}>Retry</button></div>;
 if(!job)return <div className="empty-state"><h1>Role unavailable</h1><p>This role could not be found.</p><Link to="/organizations/manage">Back to hiring workspace</Link></div>;
 const hasExisting=!!existing?.length;
 return <div className="page-stack"><section className="page-hero"><div><p className="eyebrow">Employer assessment builder</p><h1>{job?.title||"Role"} CBT</h1><p>Create role-specific multiple-choice questions. Answer keys are protected from applicants and scoring happens on the server.</p></div></section>
 {hasExisting&&<div className="flex items-start gap-2 rounded-2xl bg-trust-light p-4 text-sm leading-6 text-trust-dark"><CheckCircle2 size={18}/><div className="min-w-0"><strong className="block">CBT already set.</strong><span className="block">The saved questions are loaded below. Apply changes only when you want to replace that saved version.</span></div></div>}
 <form onSubmit={submit} aria-busy={save.isPending||update.isPending}><fieldset disabled={save.isPending||update.isPending} className="space-y-3">
  <label className="flex max-w-xs items-center gap-3 rounded-2xl border border-paper-dim bg-white p-4 text-sm font-semibold"><Clock3 size={18}/><span>Time limit</span><input type="number" min="1" max="180" value={minutes} onChange={e=>setMinutes(Number(e.target.value)||1)} className="w-20 rounded-xl border p-2"/><span>minutes</span></label>
  {isLoading?<div className="feed-skeleton"/>:rows.map((row,i)=><section key={i} className="rounded-2xl border border-paper-dim bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Question {i+1}</h2>{rows.length>1&&<button type="button" onClick={()=>setRows(rows.filter((_,n)=>n!==i))} aria-label={"Remove question "+(i+1)} className="rounded-full p-2 text-flag"><Trash2 size={16}/></button>}</div><textarea aria-label={"Question "+(i+1)} required rows={2} value={row.questionText} onChange={e=>patch(i,{questionText:e.target.value})} placeholder="Question" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-3 grid gap-2 sm:grid-cols-2">{row.choices.map((choice,n)=><div key={n} className="flex items-center gap-2"><input aria-label={"Question "+(i+1)+", option "+(n+1)} required={n<2} value={choice} onChange={e=>{const old=choice;const choices=[...row.choices];choices[n]=e.target.value;patch(i,{choices,correctChoice:old&&row.correctChoice===old?e.target.value:row.correctChoice});}} placeholder={"Option "+(n+1)} className="min-w-0 flex-1 rounded-xl border p-3"/><input disabled={!choice.trim()} aria-label={"Use option "+(n+1)+" as the correct answer for question "+(i+1)} type="radio" name={"correct-"+i} checked={!!choice&&row.correctChoice===choice} onChange={()=>patch(i,{correctChoice:choice})} title="Correct answer"/></div>)}</div><p className="mt-2 text-xs text-ink-faint">Enter at least two distinct options, then select the correct answer. Extra options are optional.</p></section>)}
  <button type="button" onClick={()=>setRows([...rows,blank()])} className="inline-flex items-center gap-2 rounded-xl border border-black/10 px-4 py-2.5 text-sm font-semibold"><Plus size={16}/>Add question</button>{(validationError||draftError)&&<p role="alert" className="text-flag">{validationError||draftError}</p>}{saved&&<p role="status">Assessment saved.</p>}{save.error&&<p className="text-sm text-flag">{(save.error as Error).message}</p>}{update.error&&<p className="text-sm text-flag">{(update.error as Error).message}</p>}
  <div className="sticky bottom-20 rounded-2xl bg-white/95 p-3 shadow-xl backdrop-blur sm:bottom-4"><button disabled={save.isPending||update.isPending} className="w-full rounded-xl bg-ink px-4 py-3 font-semibold text-white disabled:opacity-40">{save.isPending||update.isPending?"Saving assessment…":hasExisting?"Apply CBT changes":"Save CBT questions"}</button><Link to="/organizations/manage" className="mt-2 block text-center text-xs font-semibold text-brand-dark">Back to hiring workspace</Link></div>
 </fieldset></form></div>;
}