import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { CheckCircle2, Clock3, Plus, Trash2 } from "lucide-react";
import { useHiringJob, useRecruiterCbtQuestions, useSaveCbtQuestions, useUpdateJob } from "../hooks/useHiring";
type Draft={questionText:string;choices:string[];correctChoice:string};
const blank=():Draft=>({questionText:"",choices:["","","",""],correctChoice:""});
export function JobCbtBuilder(){
 const {id}=useParams();const {data:job}=useHiringJob(id);const {data:existing,isLoading}=useRecruiterCbtQuestions(id);const save=useSaveCbtQuestions(id||"");const update=useUpdateJob(id||"",job?.organization_id||"");
 const [rows,setRows]=useState<Draft[]>([blank()]);const [minutes,setMinutes]=useState(15);const [loaded,setLoaded]=useState(false);
 useEffect(()=>{if(!loaded&&existing){setRows(existing.length?existing.map((q:any)=>({questionText:q.question_text,choices:Array.isArray(q.choices)?q.choices:["","","",""],correctChoice:q.correct_choice||""})):[blank()]);setMinutes(Math.max(1,Math.round((job?.cbt_time_limit_seconds||900)/60)));setLoaded(true)}},[existing,job,loaded]);
 function patch(i:number,next:Partial<Draft>){setRows(rows.map((r,n)=>n===i?{...r,...next}:r))}
 async function submit(e:React.FormEvent){e.preventDefault();const clean=rows.map(r=>({...r,questionText:r.questionText.trim(),choices:r.choices.map(x=>x.trim()).filter(Boolean)})).filter(r=>r.questionText&&r.choices.length>=2&&r.correctChoice);if(clean.some(r=>!r.choices.includes(r.correctChoice)))return;await save.mutateAsync(clean);await update.mutateAsync({cbt_time_limit_seconds:Math.max(60,Math.min(10800,Math.round(minutes*60)))});}
 const hasExisting=!!existing?.length;
 return <div className="page-stack"><section className="page-hero"><div><p className="eyebrow">Employer assessment builder</p><h1>{job?.title||"Role"} CBT</h1><p>Create role-specific multiple-choice questions. Answer keys are protected from applicants and scoring happens on the server.</p></div></section>
 {hasExisting&&<div className="flex items-center gap-2 rounded-2xl bg-trust-light p-4 text-sm text-trust-dark"><CheckCircle2 size={18}/><strong>CBT already set.</strong><span> You are editing the existing assessment; saving updates it rather than creating a second test.</span></div>}
 <form onSubmit={submit} className="space-y-3">
  <label className="flex max-w-xs items-center gap-3 rounded-2xl border border-paper-dim bg-white p-4 text-sm font-semibold"><Clock3 size={18}/><span>Time limit</span><input type="number" min="1" max="180" value={minutes} onChange={e=>setMinutes(Number(e.target.value)||1)} className="w-20 rounded-xl border p-2"/><span>minutes</span></label>
  {isLoading?<div className="feed-skeleton"/>:rows.map((row,i)=><section key={i} className="rounded-2xl border border-paper-dim bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Question {i+1}</h2>{rows.length>1&&<button type="button" onClick={()=>setRows(rows.filter((_,n)=>n!==i))} className="rounded-full p-2 text-flag"><Trash2 size={16}/></button>}</div><textarea required rows={2} value={row.questionText} onChange={e=>patch(i,{questionText:e.target.value})} placeholder="Question" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-3 grid gap-2 sm:grid-cols-2">{row.choices.map((choice,n)=><div key={n} className="flex items-center gap-2"><input required value={choice} onChange={e=>{const old=choice;const choices=[...row.choices];choices[n]=e.target.value;patch(i,{choices,correctChoice:row.correctChoice===old?e.target.value:row.correctChoice});}} placeholder={"Option "+(n+1)} className="min-w-0 flex-1 rounded-xl border p-3"/><input type="radio" name={"correct-"+i} checked={!!choice&&row.correctChoice===choice} onChange={()=>patch(i,{correctChoice:choice})} title="Correct answer"/></div>)}</div><p className="mt-2 text-xs text-ink-faint">Select the radio button beside the correct option.</p></section>)}
  <button type="button" onClick={()=>setRows([...rows,blank()])} className="inline-flex items-center gap-2 rounded-xl border border-black/10 px-4 py-2.5 text-sm font-semibold"><Plus size={16}/>Add question</button>{save.error&&<p className="text-sm text-flag">{(save.error as Error).message}</p>}{update.error&&<p className="text-sm text-flag">{(update.error as Error).message}</p>}
  <div className="sticky bottom-20 rounded-2xl bg-white/95 p-3 shadow-xl backdrop-blur sm:bottom-4"><button disabled={save.isPending||update.isPending} className="w-full rounded-xl bg-ink px-4 py-3 font-semibold text-white disabled:opacity-40">{save.isPending||update.isPending?"Saving assessment…":hasExisting?"Apply CBT changes":"Save CBT questions"}</button><Link to="/organizations/manage" className="mt-2 block text-center text-xs font-semibold text-brand-dark">Back to hiring workspace</Link></div>
 </form></div>;
}