import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Briefcase, Check, ShieldCheck } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { useCreateJob, useMyOrganizations } from "../hooks/useHiring";

type Screening={questionText:string;answerType:"short_text"|"number"|"date"|"yes_no"|"single_choice";choices:string[];required:boolean};
const STEPS=["Basics","Pay & timing","Description","Screening","Review"];
const defaults={title:"",roleType:"",rank:"Entry",employmentType:"Full-time",workStyle:"On-site",location:"",payMin:"",payMax:"",closesAt:"",description:"",requirements:"",requiresCbt:false,screening:[{questionText:"Expected monthly pay?",answerType:"number",choices:[],required:true},{questionText:"Years of experience?",answerType:"number",choices:[],required:true},{questionText:"Available start date?",answerType:"date",choices:[],required:true}] as Screening[]};

export function JobPostWizard(){
 const {organizationId}=useParams(); const nav=useNavigate(); const location=useLocation(); const create=useCreateJob(); const {data}=useMyOrganizations();
 const org=useMemo(()=>data?.map((x:any)=>x.organizations).find((x:any)=>x?.id===organizationId),[data,organizationId]);
 const duplicate=(location.state as any)?.duplicate;
 const [step,setStep]=useState(0);
 const [f,setF]=useState({...defaults,...(duplicate?{title:duplicate.title+" (copy)",roleType:duplicate.role_type,rank:duplicate.rank,employmentType:duplicate.employment_type,workStyle:duplicate.work_style,location:duplicate.location,payMin:duplicate.pay_min?.toString()??"",payMax:duplicate.pay_max?.toString()??"",description:duplicate.description,requirements:(duplicate.requirements??[]).join("\n"),requiresCbt:!!duplicate.requires_cbt}:{}),location:duplicate?.location??org?.location??""});
 const verified=!!org&&(org.verified===true||org.verification_status==="verified");
 const canNext=step!==0||!!f.title.trim()&&!!f.roleType.trim()&&!!f.location.trim();
 async function save(){if(!organizationId)return;const result=await create.mutateAsync({organizationId,title:f.title,roleType:f.roleType,rank:f.rank,employmentType:f.employmentType,workStyle:f.workStyle,location:f.location,payMin:f.payMin?Number(f.payMin):undefined,payMax:f.payMax?Number(f.payMax):undefined,description:f.description,requirements:f.requirements.split("\n").map((x:string)=>x.trim()).filter(Boolean),requiresCbt:f.requiresCbt,closesAt:f.closesAt?new Date(f.closesAt+"T23:59:59").toISOString():undefined,screening:f.screening});nav("/organizations/manage",{state:{jobCreated:true,published:result.published}});}
 return <div className="page-stack">
  <section className="page-hero"><div className="page-icon bg-brand-light text-brand-dark"><Briefcase size={22}/></div><div><p className="eyebrow">Organization hiring</p><h1>{duplicate?"Duplicate role":"Post a role"}</h1><p>A guided setup keeps each vacancy clear, complete and ready for applicants.</p></div></section>
  <div className="rounded-3xl border border-paper-dim bg-white p-5 shadow-card sm:p-7">
   <div className="mb-6 flex gap-2 overflow-x-auto">{STEPS.map((s,i)=><div key={s} className={"shrink-0 rounded-full px-3 py-1.5 text-xs font-semibold "+(i===step?"bg-ink text-white":i<step?"bg-brand-light text-brand-dark":"bg-paper text-ink-faint")}>{i<step?<Check size={12} className="mr-1 inline"/>:null}{i+1}. {s}</div>)}</div>
   {!verified&&<div className="mb-5 flex gap-2 rounded-2xl bg-opportunity-light p-3 text-sm text-ink-light"><ShieldCheck size={18} className="shrink-0 text-opportunity-dark"/><span>Your organization can prepare this role now. It will remain a draft until verification.</span></div>}
   {step===0&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Role title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="e.g. Front Desk Supervisor" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Role type<input value={f.roleType} onChange={e=>setF({...f,roleType:e.target.value})} placeholder="e.g. Hospitality" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Seniority<select value={f.rank} onChange={e=>setF({...f,rank:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{["Entry","Junior","Senior","Supervisor","Manager"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Employment<select value={f.employmentType} onChange={e=>setF({...f,employmentType:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{["Full-time","Part-time","Contract"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Work style<select value={f.workStyle} onChange={e=>setF({...f,workStyle:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{["On-site","Hybrid","Remote"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Location<input value={f.location} onChange={e=>setF({...f,location:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label></div>}
   {step===1&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Minimum monthly pay<input type="number" min="0" value={f.payMin} onChange={e=>setF({...f,payMin:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Maximum monthly pay<input type="number" min="0" value={f.payMax} onChange={e=>setF({...f,payMax:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Closing date<input type="date" value={f.closesAt} onChange={e=>setF({...f,closesAt:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={f.requiresCbt} onChange={e=>setF({...f,requiresCbt:e.target.checked})}/>Require CBT assessment</label></div>}
   {step===2&&<div className="space-y-4"><label className="block text-sm font-semibold">Role description<textarea rows={7} value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Responsibilities, team, expectations and what success looks like…" className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm font-semibold">Requirements — one per line<textarea rows={6} value={f.requirements} onChange={e=>setF({...f,requirements:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label></div>}
   {step===3&&<div><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">Application screening</h2><p className="text-xs text-ink-faint">Ask only what helps you review candidates.</p></div><button type="button" onClick={()=>setF({...f,screening:[...f.screening,{questionText:"",answerType:"short_text",choices:[],required:true}]})} className="rounded-xl bg-paper px-3 py-2 text-xs font-semibold">+ Add question</button></div><div className="space-y-3">{f.screening.map((q,i)=><div key={i} className="grid gap-2 rounded-2xl bg-paper p-3 sm:grid-cols-[1fr_150px_auto]"><input value={q.questionText} onChange={e=>{const s=[...f.screening];s[i]={...q,questionText:e.target.value};setF({...f,screening:s})}} placeholder="Question" className="rounded-xl border bg-white p-3"/><select value={q.answerType} onChange={e=>{const s=[...f.screening];s[i]={...q,answerType:e.target.value as Screening["answerType"]};setF({...f,screening:s})}} className="rounded-xl border bg-white p-3"><option value="short_text">Short text</option><option value="number">Number</option><option value="date">Date</option><option value="yes_no">Yes / No</option><option value="single_choice">Multiple choice</option></select><button type="button" onClick={()=>setF({...f,screening:f.screening.filter((_,n)=>n!==i)})} className="px-2 text-xs font-semibold text-flag">Remove</button></div>)}</div></div>}
   {step===4&&<div className="space-y-4"><div className="rounded-2xl bg-paper p-5"><p className="eyebrow">Preview</p><h2 className="mt-1 text-2xl font-bold">{f.title||"Untitled role"}</h2><p className="mt-1 text-sm text-ink-light">{f.rank} · {f.employmentType} · {f.workStyle} · {f.location}</p>{(f.payMin||f.payMax)&&<p className="mt-3 text-sm font-semibold">Pay: {f.payMin||"—"} – {f.payMax||"—"}</p>}<p className="mt-4 whitespace-pre-wrap text-sm leading-6">{f.description||"No description yet."}</p><p className="mt-4 text-xs text-ink-faint">{f.screening.filter(x=>x.questionText.trim()).length} screening questions {f.requiresCbt?"· CBT required":""}</p></div>{create.error&&<p className="text-sm text-flag">{(create.error as Error).message}</p>}</div>}
   <div className="mt-7 flex items-center justify-between border-t border-paper-dim pt-4"><button type="button" onClick={()=>step?setStep(step-1):nav("/organizations/manage")} className="inline-flex items-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold hover:bg-paper"><ArrowLeft size={15}/>{step?"Back":"Cancel"}</button>{step<4?<button type="button" disabled={!canNext} onClick={()=>setStep(step+1)} className="inline-flex items-center gap-1.5 rounded-xl bg-ink px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Continue <ArrowRight size={15}/></button>:<button type="button" disabled={create.isPending} onClick={save} className="rounded-xl bg-brand px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{create.isPending?"Saving…":verified?"Publish role":"Save draft"}</button>}</div>
  </div>
 </div>
}
