import { validateJobForm } from "../lib/jobValidation";
import { usePersistentDraft } from "../hooks/usePersistentDraft";
import { ApplicationUploadFields } from "../components/ApplicationUploadFields";
import { DEFAULT_DOCUMENT_TYPES, documentMime, validateApplicationDefaults } from "../lib/applicationUploads";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Briefcase, Check, ShieldCheck } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { useCreateJob, useMyOrganizations, useUpdateJob, useScreeningQuestions } from "../hooks/useHiring";
import { supabase } from "../lib/supabase";
import { useAuth } from "../store/auth";

type Screening={questionText:string;answerType:"short_text"|"number"|"date"|"yes_no"|"single_choice";choices:string[];required:boolean};
const STEPS=["Basics","Pay & timing","Description","Screening","Review"];
const defaults={title:"",roleType:"",rank:"Entry",employmentType:"Full-time",workStyle:"On-site",location:"",payMin:"",payMax:"",closesAt:"",description:"",requirements:"",requiresCbt:false,cbtMinutes:"15",applicationDocumentLabel:"CV / résumé",applicationDocumentLabels:["CV / résumé"],applicationDocumentAccept:DEFAULT_DOCUMENT_TYPES,applicationDocumentRequired:true,passportPhotoRequired:false,coverLetterRequired:false,screening:[{questionText:"Expected monthly pay?",answerType:"number",choices:[],required:true},{questionText:"Years of experience?",answerType:"number",choices:[],required:true},{questionText:"Available start date?",answerType:"date",choices:[],required:true}] as Screening[]};

export function JobPostWizard(){
 const {organizationId}=useParams(); const nav=useNavigate(); const {userId}=useAuth(); const location=useLocation(); const create=useCreateJob(); const {data}=useMyOrganizations();
 const org=useMemo(()=>data?.map((x:any)=>x.organizations).find((x:any)=>x?.id===organizationId),[data,organizationId]);
 const duplicate=(location.state as any)?.duplicate; const edit=(location.state as any)?.edit; const source=edit??duplicate; const update=useUpdateJob(edit?.id??"",organizationId??"");
 const screeningQuery=useScreeningQuestions(source?.id);
 const [saveError,setSaveError]=useState("");const [saving,setSaving]=useState(false);
 const [step,setStep]=useState(0);
 const [requestId]=useState(()=>crypto.randomUUID());
 const [jobMedia,setJobMedia]=useState<File[]>([]);
 const draftKey=`possara-job-post-draft:${userId}:${organizationId||"none"}:${edit?.id||(duplicate?"copy-"+duplicate.id:"new")}`;
 const [f,setF,clearDraft,draftError]=usePersistentDraft(draftKey,{...defaults,requestId,...(org?.application_defaults?{applicationDocumentLabels:org.application_defaults.labels,applicationDocumentAccept:org.application_defaults.accept,applicationDocumentRequired:org.application_defaults.required}:{}),...(source?{title:source.title+(duplicate?" (copy)":""),roleType:source.role_type,rank:source.rank,employmentType:source.employment_type,workStyle:source.work_style,location:source.location,payMin:source.pay_min?.toString()??"",payMax:source.pay_max?.toString()??"",closesAt:source.closes_at?new Date(new Date(source.closes_at).getTime()-new Date(source.closes_at).getTimezoneOffset()*60000).toISOString().slice(0,10):"",description:source.description,requirements:(source.requirements??[]).join("\n"),requiresCbt:!!source.requires_cbt,cbtMinutes:String(Math.round((source.cbt_time_limit_seconds||900)/60)),applicationDocumentLabel:source.application_document_label||"CV / résumé",applicationDocumentLabels:source.application_document_labels?.length?source.application_document_labels:[source.application_document_label||"CV / résumé"],applicationDocumentAccept:source.application_document_accept||DEFAULT_DOCUMENT_TYPES,applicationDocumentRequired:source.application_document_required!==false,passportPhotoRequired:!!source.passport_photo_required,coverLetterRequired:!!source.cover_letter_required}:{}),location:source?.location??org?.location??"",...(source&&screeningQuery.data?{screening:screeningQuery.data.map(q=>({questionText:q.question_text,answerType:q.answer_type,choices:q.choices??[],required:q.required}))}:{})});
 const verified=!!org&&(org.verified===true||org.verification_status==="verified");
 const canNext=step!==0||!!f.title.trim()&&!!f.roleType.trim()&&!!f.location.trim();
 async function uploadJobMedia(){const urls:string[]=[];for(const [index,file] of jobMedia.entries()){if(file.size>10*1024*1024)throw new Error(`${file.name} is larger than 10MB.`);if(!["application/pdf","image/jpeg","image/png","image/webp"].includes(documentMime(file)))throw new Error("Job media must be PDF, JPG, PNG or WebP.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${userId}/${organizationId}/${Date.now()}-${index}-${safe}`;const {error}=await supabase.storage.from("opportunity-media").upload(path,new File([file],file.name,{type:documentMime(file)}),{contentType:documentMime(file),upsert:false});if(error)throw error;urls.push(supabase.storage.from("opportunity-media").getPublicUrl(path).data.publicUrl);}return urls;}
 async function save(publish=false){if(!organizationId||saving)return;setSaveError("");setSaving(true);try{if(!f.requestId)setF({...f,requestId});validateJobForm(f,publish,!edit);const fields=validateApplicationDefaults({labels:f.applicationDocumentLabels,accept:f.applicationDocumentAccept,required:f.applicationDocumentRequired});const mediaUrls=jobMedia.length?await uploadJobMedia():(source?.job_media_urls??[]);if(edit){await update.mutateAsync({title:f.title.trim(),role_type:f.roleType.trim(),rank:f.rank,employment_type:f.employmentType,work_style:f.workStyle,location:f.location.trim(),pay_min:f.payMin?Number(f.payMin):null,pay_max:f.payMax?Number(f.payMax):null,description:f.description.trim(),requirements:f.requirements.split("\n").map((x:string)=>x.trim()).filter(Boolean),requires_cbt:f.requiresCbt,cbt_time_limit_seconds:Math.max(60,Number(f.cbtMinutes||15)*60),application_document_label:f.applicationDocumentLabels[0]||f.applicationDocumentLabel,application_document_labels:fields.labels,application_document_accept:fields.accept,job_media_urls:mediaUrls,application_document_required:f.applicationDocumentRequired,passport_photo_required:f.passportPhotoRequired,cover_letter_required:f.coverLetterRequired,status:publish?"open":"draft",closes_at:f.closesAt?new Date(f.closesAt+"T23:59:59").toISOString():null});clearDraft();nav("/organizations/manage",{state:{jobUpdated:true}});return;}const result=await create.mutateAsync({requestId:f.requestId||requestId,organizationId,title:f.title,roleType:f.roleType,rank:f.rank,employmentType:f.employmentType,workStyle:f.workStyle,location:f.location,payMin:f.payMin?Number(f.payMin):undefined,payMax:f.payMax?Number(f.payMax):undefined,description:f.description,requirements:f.requirements.split("\n").map((x:string)=>x.trim()).filter(Boolean),requiresCbt:f.requiresCbt,cbtTimeLimitSeconds:Math.max(60,Number(f.cbtMinutes||15)*60),applicationDocumentLabel:f.applicationDocumentLabels[0]||f.applicationDocumentLabel,applicationDocumentLabels:fields.labels,applicationDocumentAccept:fields.accept,jobMediaUrls:mediaUrls,applicationDocumentRequired:f.applicationDocumentRequired,passportPhotoRequired:f.passportPhotoRequired,coverLetterRequired:f.coverLetterRequired,publish,closesAt:f.closesAt?new Date(f.closesAt+"T23:59:59").toISOString():undefined,screening:f.screening});clearDraft();nav("/organizations/manage",{state:{jobCreated:true,published:result.published}});}catch(error){setSaveError(error instanceof Error?error.message:"Could not save this role. Please retry.");}finally{setSaving(false);}}
 return <div className="page-stack">{draftError&&<p role="alert" className="text-flag">{draftError}</p>}{saveError&&<p role="alert" className="rounded-xl bg-white p-4 text-flag">{saveError}</p>}
  <section className="page-hero"><div className="page-icon bg-brand-light text-brand-dark"><Briefcase size={22}/></div><div><p className="eyebrow">Organization hiring</p><h1>{edit?"Edit role":duplicate?"Duplicate role":"Post a role"}</h1><p>A guided setup keeps each vacancy clear, complete and ready for applicants.</p></div></section>
  <div className="rounded-3xl border border-paper-dim bg-white p-5 shadow-card sm:p-7">
   <div className="mb-6 flex gap-2 overflow-x-auto">{STEPS.map((s,i)=><div key={s} className={"shrink-0 rounded-full px-3 py-1.5 text-xs font-semibold "+(i===step?"bg-ink text-white":i<step?"bg-brand-light text-brand-dark":"bg-paper text-ink-faint")}>{i<step?<Check size={12} className="mr-1 inline"/>:null}{i+1}. {s}</div>)}</div>
   {!verified&&<div className="mb-5 flex gap-2 rounded-2xl bg-opportunity-light p-3 text-sm text-ink-light"><ShieldCheck size={18} className="shrink-0 text-opportunity-dark"/><span>Your organization is still under verification. You can publish jobs now; the organization will continue to show its current verification status until review is complete.</span></div>}
   {step===0&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Role title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="e.g. Front Desk Supervisor" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Role type<input value={f.roleType} onChange={e=>setF({...f,roleType:e.target.value})} placeholder="e.g. Hospitality" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Seniority<select value={f.rank} onChange={e=>setF({...f,rank:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{["Entry","Junior","Senior","Supervisor","Manager"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Employment<select value={f.employmentType} onChange={e=>setF({...f,employmentType:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{["Full-time","Part-time","Contract"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Work style<select value={f.workStyle} onChange={e=>setF({...f,workStyle:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{["On-site","Hybrid","Remote"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Location<input value={f.location} onChange={e=>setF({...f,location:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label></div>}
   {step===1&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Minimum monthly pay<input type="number" min="0" value={f.payMin} onChange={e=>setF({...f,payMin:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Maximum monthly pay<input type="number" min="0" value={f.payMax} onChange={e=>setF({...f,payMax:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-semibold">Closing date<input type="date" value={f.closesAt} onChange={e=>setF({...f,closesAt:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><div className="sm:col-span-2"><ApplicationUploadFields value={{labels:f.applicationDocumentLabels,accept:f.applicationDocumentAccept,required:f.applicationDocumentRequired}} onChange={value=>setF({...f,applicationDocumentLabels:value.labels,applicationDocumentAccept:value.accept,applicationDocumentRequired:value.required})}/></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={f.passportPhotoRequired} onChange={e=>setF({...f,passportPhotoRequired:e.target.checked})}/>Require passport/applicant photo</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={f.coverLetterRequired} onChange={e=>setF({...f,coverLetterRequired:e.target.checked})}/>Require cover letter</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={f.requiresCbt} onChange={e=>setF({...f,requiresCbt:e.target.checked})}/>Require CBT assessment</label>{f.requiresCbt&&<label className="text-sm font-semibold">CBT time limit (minutes)<input type="number" min="1" max="180" value={f.cbtMinutes} onChange={e=>setF({...f,cbtMinutes:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label>}</div>}
   {step===2&&<div className="space-y-4"><label className="block rounded-2xl border border-dashed border-black/20 p-4 text-sm font-semibold">Job images / PDF <span className="font-normal text-ink-faint">(optional)</span><p className="mt-1 text-xs font-normal text-ink-faint">Add images or PDFs applicants can view with this vacancy. Up to 6 files, 10MB each.</p><input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setJobMedia(Array.from(e.target.files??[]).slice(0,6))} className="mt-3 block w-full text-sm"/>{jobMedia.length>0&&<p className="mt-2 text-xs text-trust-dark">{jobMedia.length} file(s) selected</p>}</label><label className="block text-sm font-semibold">Role description<textarea rows={7} value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Responsibilities, team, expectations and what success looks like…" className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm font-semibold">Requirements — one per line<textarea rows={6} value={f.requirements} onChange={e=>setF({...f,requirements:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label></div>}
   {step===3&&<div>{edit&&<p className="mb-4 text-sm text-ink-light">Existing screening questions are kept unchanged to preserve applicant answers. Duplicate this role to use a different screening form.</p>}<fieldset disabled={!!edit||!!source&&screeningQuery.isLoading}><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">Application screening</h2><p className="text-xs text-ink-faint">Ask only what helps you review candidates.</p></div><button type="button" onClick={()=>setF({...f,screening:[...f.screening,{questionText:"",answerType:"short_text",choices:[],required:true}]})} className="rounded-xl bg-paper px-3 py-2 text-xs font-semibold">+ Add question</button></div><div className="space-y-3">{f.screening.map((q,i)=><div key={i} className="rounded-2xl bg-paper p-3"><div className="grid gap-2 sm:grid-cols-[1fr_150px_auto]"><input value={q.questionText} onChange={e=>{const s=[...f.screening];s[i]={...q,questionText:e.target.value};setF({...f,screening:s})}} placeholder="Field or question" className="rounded-xl border bg-white p-3"/><select value={q.answerType} onChange={e=>{const s=[...f.screening];s[i]={...q,answerType:e.target.value as Screening["answerType"]};setF({...f,screening:s})}} className="rounded-xl border bg-white p-3"><option value="short_text">Short text</option><option value="number">Number</option><option value="date">Date</option><option value="yes_no">Yes / No</option><option value="single_choice">Multiple choice</option></select><button type="button" onClick={()=>setF({...f,screening:f.screening.filter((_,n)=>n!==i)})} className="px-2 text-xs font-semibold text-flag">Remove</button></div><div className="mt-2 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={q.required} onChange={e=>{const s=[...f.screening];s[i]={...q,required:e.target.checked};setF({...f,screening:s})}}/>{q.required?"Required":"Optional"}</label>{q.answerType==="single_choice"&&<input value={q.choices.join(", ")} onChange={e=>{const s=[...f.screening];s[i]={...q,choices:e.target.value.split(",").map(x=>x.trim())};setF({...f,screening:s})}} placeholder="Choices separated by commas" className="min-w-64 flex-1 rounded-xl border bg-white p-2 text-sm"/>}</div></div>)}</div></fieldset></div>}
   {step===4&&<div className="space-y-4"><div className="rounded-2xl bg-paper p-4 sm:p-5"><p className="eyebrow">Preview</p><h2 className="mt-1 break-words text-2xl font-bold">{f.title||"Untitled role"}</h2><p className="mt-1 text-sm text-ink-light">{f.rank} · {f.employmentType} · {f.workStyle} · {f.location}</p>{(f.payMin||f.payMax)&&<p className="mt-3 text-sm font-semibold">Pay: {f.payMin||"—"} – {f.payMax||"—"}</p>}<p className="mt-4 whitespace-pre-wrap text-sm leading-6">{f.description||"No description yet."}</p><p className="mt-4 text-xs text-ink-faint">{f.screening.filter(x=>x.questionText.trim()).length} screening questions {f.requiresCbt?"· CBT required":""}</p></div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-xl border border-paper-dim bg-white p-3"><p className="text-sm font-semibold">Save draft</p><p className="mt-1 text-xs leading-5 text-ink-faint">Keeps this role private to your organization team. It will not appear in Jobs or accept applications.</p></div><div className="rounded-xl border border-trust/20 bg-trust-light p-3"><p className="text-sm font-semibold text-trust-dark">Publish job</p><p className="mt-1 text-xs leading-5 text-ink-light">Makes this role live in POSSARA Jobs and opens applications immediately.</p></div></div>{(create.error||update.error)&&<p className="rounded-xl bg-flag-light px-3 py-2 text-sm font-medium text-flag-dark">{((create.error||update.error) as Error).message}</p>}</div>}
   <div className="mt-7 flex flex-col-reverse gap-2 border-t border-paper-dim pt-4 sm:flex-row sm:items-center sm:justify-between"><button type="button" onClick={()=>step?setStep(step-1):nav("/organizations/manage")} className="inline-flex min-h-11 items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold hover:bg-paper"><ArrowLeft size={15}/>{step?"Back":"Cancel"}</button>{step<4?<button type="button" disabled={!canNext} onClick={()=>setStep(step+1)} className="inline-flex min-h-11 items-center justify-center gap-1.5 rounded-xl bg-ink px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Continue <ArrowRight size={15}/></button>:<div className="grid grid-cols-2 gap-2 sm:flex"><button type="button" disabled={saving||create.isPending||update.isPending} onClick={()=>void save(false).catch(()=>undefined)} className="min-h-11 rounded-xl border border-ink-faint/25 px-3 py-2.5 text-sm font-semibold disabled:opacity-50">Save draft</button><button type="button" disabled={saving||create.isPending||update.isPending} onClick={()=>void save(true).catch(()=>undefined)} className="min-h-11 rounded-xl bg-brand px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{create.isPending||update.isPending?"Saving…":"Publish job"}</button></div>}</div>
  </div>
 </div>
}
