import { useEffect, useRef, useState } from "react";
import { useParams, Link, Navigate } from "react-router-dom";
import { MessageCircle, Send } from "lucide-react";
import { useConversations, useThread, useSendMessage, useMarkThreadRead } from "../hooks/useMessages";
import { useAuth } from "../store/auth";

function ConversationList({ activeUserId }: { activeUserId?: string }) {
  const { data: conversations, isLoading } = useConversations();
  return <div className="w-full shrink-0 border-r border-paper-dim pr-4 sm:w-64"><h2 className="mb-2 text-sm font-medium text-ink-faint">Conversations</h2>{isLoading&&<p className="text-sm text-ink-light">Loading…</p>}{!isLoading&&conversations?.length===0&&<p className="text-sm text-ink-light">No conversations yet — visit someone's profile on Connect and message them.</p>}<div className="space-y-1">{conversations?.map((c)=><Link key={c.otherUserId} to={`/messages/${c.otherUserId}`} className={`flex items-center gap-2.5 rounded-xl px-2 py-2 transition hover:bg-paper-dim ${activeUserId===c.otherUserId?"bg-paper-dim":""}`}>{c.otherUser?.avatar_url?<img src={c.otherUser.avatar_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:<div className="flex h-9 w-9 items-center justify-center rounded-full bg-trust-light text-xs font-medium text-trust-dark">{(c.otherUser?.full_name??"?").charAt(0).toUpperCase()}</div>}<div className="min-w-0 flex-1"><p className={`truncate text-sm ${c.unread?"font-semibold":"font-medium"}`}>{c.otherUser?.full_name??"Member"}</p><p className="truncate text-xs text-ink-faint">{c.lastMessage}</p></div>{c.unread&&<span className="h-2 w-2 shrink-0 rounded-full bg-brand"/>}</Link>)}</div></div>;
}
function Thread({ otherUserId }: { otherUserId: string }) {
  const { userId }=useAuth(); const {data:messages,isLoading}=useThread(otherUserId); const sendMessage=useSendMessage(otherUserId); const markRead=useMarkThreadRead(otherUserId); const [text,setText]=useState(""); const bottomRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{markRead.mutate();},[otherUserId]);
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"});},[messages?.length]);
  async function handleSend(e:React.FormEvent){e.preventDefault();if(!text.trim())return;await sendMessage.mutateAsync(text.trim());setText("");}
  return <div className="flex min-w-0 flex-1 flex-col"><div className="flex-1 space-y-2 overflow-y-auto px-2" style={{maxHeight:"60vh"}}>{isLoading&&<p className="text-sm text-ink-light">Loading…</p>}{messages?.map((m)=><div key={m.id} className={`flex ${m.sender_id===userId?"justify-end":"justify-start"}`}><div className={`max-w-xs rounded-2xl px-3.5 py-2 text-sm ${m.sender_id===userId?"bg-brand text-white":"bg-paper-dim text-ink"}`}>{m.content}</div></div>)}<div ref={bottomRef}/></div><form onSubmit={handleSend} className="mt-3 flex gap-2 border-t border-paper-dim pt-3"><input maxLength={4000} value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…" className="flex-1 rounded-full border border-ink-faint/30 px-4 py-2 text-sm outline-none focus:border-brand"/><button type="submit" disabled={!text.trim()||sendMessage.isPending} className="flex h-9 w-9 items-center justify-center rounded-full bg-brand text-white disabled:opacity-40" aria-label="Send"><Send size={15}/></button></form>{sendMessage.error&&<p className="mt-2 text-sm text-flag">{(sendMessage.error as Error).message}</p>}</div>;
}
export function Messages(){const {userId:otherUserId}=useParams<{userId:string}>();const {userId}=useAuth();if(otherUserId===userId)return <Navigate to="/messages" replace/>;return <div><h1 className="mb-4 text-2xl">Messages</h1><div className="flex flex-col gap-4 rounded-2xl border border-paper-dim bg-white p-4 shadow-sm sm:flex-row"><ConversationList activeUserId={otherUserId}/>{otherUserId?<Thread otherUserId={otherUserId}/>:<div className="flex flex-1 flex-col items-center justify-center py-16 text-center"><MessageCircle size={28} className="text-ink-faint"/><p className="mt-3 text-ink-light">Select a conversation, or start one from a member's profile.</p></div>}</div></div>}
