import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Bell } from "lucide-react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../store/auth";

function useNotifications(userId:string|null){return useQuery({queryKey:["notifications",userId],enabled:!!userId,queryFn:async()=>{const {data,error}=await supabase.from("notifications").select("*").order("created_at",{ascending:false}).limit(50);if(error)throw error;return data??[];}})}
function useMarkNotificationRead(){const queryClient=useQueryClient();return useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("notifications").update({read:true}).eq("id",id);if(error)throw error;},onSuccess:()=>{queryClient.invalidateQueries({queryKey:["notifications"]});queryClient.invalidateQueries({queryKey:["unread-notification-count"]});}})}
export function Notifications(){const {userId}=useAuth();const {data:notifications,isLoading}=useNotifications(userId);const markRead=useMarkNotificationRead();const navigate=useNavigate();function handleClick(n:{id:string;read:boolean|null;link:string|null}){if(!n.read)markRead.mutate(n.id);if(n.link)navigate(n.link)}return <div className="max-w-prose"><h1 className="text-2xl">Notifications</h1><p className="mt-1 text-ink-light">Opportunity, organization and social updates in one place.</p>{isLoading&&<p className="mt-4 text-ink-light">Loading…</p>}{!isLoading&&notifications?.length===0&&<div className="mt-8 flex flex-col items-center py-12 text-center"><Bell size={28} className="text-ink-faint"/><p className="mt-3 text-ink-light">You're all caught up.</p></div>}<div className="mt-4 divide-y divide-paper-dim">{notifications?.map((n)=><button key={n.id} onClick={()=>handleClick(n)} className={`block w-full py-3 text-left transition hover:bg-paper-dim/40 ${n.read?"":"font-medium"}`}><p>{n.title}</p>{n.message&&<p className="mt-0.5 text-sm font-normal text-ink-light">{n.message}</p>}<p className="mt-0.5 text-xs font-normal text-ink-faint">{new Date(n.created_at).toLocaleDateString()}</p></button>)}</div></div>}
