import { useParams, Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Globe } from "lucide-react";
import { supabase } from "../lib/supabase";
import { useOpportunities } from "../hooks/useOpportunities";
import { OpportunityCard } from "../components/OpportunityCard";
import { TrustBadge } from "../components/TrustBadge";

function useOrganization(slug:string|undefined){return useQuery({queryKey:["organization",slug],enabled:!!slug,queryFn:async()=>{const {data,error}=await supabase.from("organizations").select("*").eq("slug",slug as string).single();if(error)throw error;return data;}})}
export function OrganizationPage(){const {slug}=useParams<{slug:string}>();const {data:org,isLoading,error}=useOrganization(slug);const {data:allOpportunities}=useOpportunities({limit:50});const orgOpportunities=allOpportunities?.filter(o=>o.organization_id===org?.id);if(isLoading)return <p className="text-ink-light">Loading…</p>;if(error||!org)return <div><p className="text-flag">This organization couldn't be found.</p><Link to="/opportunities" className="mt-3 inline-block text-sm text-trust-dark underline">Back to opportunities</Link></div>;return <div className="page-stack"><Link to="/opportunities" className="inline-flex items-center gap-1.5 text-sm text-ink-light"><ArrowLeft size={15}/>All opportunities</Link><section className="rounded-2xl bg-white p-5 shadow-sm"><TrustBadge verified={org.verified??false} lastVerifiedAt={null} sponsored={org.is_sponsored}/><h1 className="mt-3 text-3xl leading-tight">{org.name}</h1>{org.description&&<p className="mt-2 text-ink-light">{org.description}</p>}{org.website&&<a href={org.website} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1.5 text-sm text-trust-dark hover:underline"><Globe size={14}/>{org.website.replace(/^https?:\/\//,"")}</a>}</section><section><h2 className="mb-3 text-sm font-medium text-ink-faint">Opportunities from {org.name}</h2>{orgOpportunities?.length===0&&<p className="text-ink-light">No active opportunities from this organization right now.</p>}{orgOpportunities?.map(opp=><OpportunityCard key={opp.id} opportunity={opp} organization={opp.organizations} category={opp.opportunity_categories}/>)}</section></div>}
