import { Link } from "react-router-dom";
import { BadgeCheck, BarChart3, BookOpenCheck, BriefcaseBusiness, Crown, Music2, ShieldCheck, Sparkles, Target } from "lucide-react";
import { usePossaraSubscription } from "../hooks/usePossaraPlus";

const FEATURES = [
  { icon: Target, title: "Opportunity Intelligence", body: "Understand why an opportunity may fit your profile, which profile signals match, and what you still need to verify before applying.", action: "Explore opportunities", to: "/opportunities" },
  { icon: BriefcaseBusiness, title: "Application Command Center", body: "Move from screenshots to action: track applications, stages, deadlines, private notes and the next thing you need to do.", action: "Open application tracker", to: "/applications" },
  { icon: BadgeCheck, title: "Growth Passport", body: "Build a private or public evidence record of skills, projects, learning, service and achievements that grows with you.", action: "Open Growth Passport", to: "/passport" },
  { icon: BarChart3, title: "Creator & profile insights", body: "See follower growth, posts published, reactions and comments received, weekly momentum and which posts are creating the strongest conversation.", action: "Open insights", to: "/insights" },
];

export function PossaraPlus() {
  const { data: subscription } = usePossaraSubscription();
  const active = subscription?.plan === "plus" && (subscription.status === "active" || subscription.status === "trialing");

  return <div className="page-stack">
    <section className="relative overflow-hidden rounded-[32px] bg-[#151020] px-6 py-8 text-white shadow-2xl sm:px-8 sm:py-10">
      <div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-violet-400/20 blur-3xl"/><div className="pointer-events-none absolute -bottom-24 left-1/3 h-52 w-52 rounded-full bg-cyan-300/10 blur-3xl"/>
      <div className="relative max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-1.5 text-xs font-semibold text-white/75"><Crown size={14}/> POSSARA+</div><h1 className="mt-5 text-3xl font-bold leading-tight sm:text-4xl">Pay for progress, not just another social badge.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/70 sm:text-base">POSSARA+ is being built around outcomes: finding stronger opportunities, actually completing applications, building evidence of growth, and understanding what is helping your profile and content move forward.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/applications" className="rounded-full bg-white px-5 py-2.5 text-sm font-bold text-[#171128]">Open premium tools</Link><Link to="/passport" className="rounded-full border border-white/20 bg-white/[.05] px-5 py-2.5 text-sm font-semibold text-white">Build Growth Passport</Link></div><p className="mt-4 text-xs text-white/45">{active ? `Your POSSARA+ ${subscription?.status === "trialing" ? "trial" : "subscription"} is active.` : "POSSARA+ tools are in product preview while billing is being prepared. No payment is being taken yet."}</p></div>
    </section>
    <section><div className="mb-3"><p className="eyebrow">What makes it worth paying for</p><h2 className="mt-1 text-2xl font-semibold">Tools that help people move forward</h2></div><div className="grid gap-3 sm:grid-cols-2">{FEATURES.map((feature) => { const Icon = feature.icon; return <article key={feature.title} className="rounded-3xl border border-black/[.06] bg-white p-5 shadow-card"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-light text-brand-dark"><Icon size={20}/></div><h3 className="mt-4 text-lg font-semibold">{feature.title}</h3><p className="mt-1 text-sm leading-6 text-ink-light">{feature.body}</p><Link to={feature.to} className="mt-4 inline-flex text-sm font-semibold text-brand-dark">{feature.action} →</Link></article>; })}</div></section>
    <section className="grid gap-3 lg:grid-cols-3"><article className="rounded-3xl bg-white p-5 shadow-card"><Music2 className="text-brand" size={22}/><h3 className="mt-3 font-semibold">POSSARA Music</h3><p className="mt-1 text-sm leading-6 text-ink-light">Original melodies, approved artist sounds and reusable tracks make Moments expressive without depending on commercial-label music at launch.</p></article><article className="rounded-3xl bg-white p-5 shadow-card"><ShieldCheck className="text-brand" size={22}/><h3 className="mt-3 font-semibold">Trust over noise</h3><p className="mt-1 text-sm leading-6 text-ink-light">Premium intelligence explains the evidence behind a match instead of pretending an algorithm can guarantee scholarship or job eligibility.</p></article><article className="rounded-3xl bg-white p-5 shadow-card"><BookOpenCheck className="text-brand" size={22}/><h3 className="mt-3 font-semibold">AVORA comes later</h3><p className="mt-1 text-sm leading-6 text-ink-light">When AVORA is fully ready, it can strengthen the student tier. POSSARA+ does not depend on unfinished AVORA functionality to justify its value.</p></article></section>
    <section className="rounded-3xl border border-brand/15 bg-brand-light/40 p-5 sm:p-6"><div className="flex items-start gap-3"><Sparkles className="mt-1 shrink-0 text-brand-dark" size={20}/><div><h2 className="text-lg font-semibold">The paid promise</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-ink-light">Free POSSARA should remain genuinely useful for community, basic opportunity discovery and connection. POSSARA+ should charge for deeper organisation, intelligence, evidence and professional/student progress tools — things that save time or improve a real-world outcome.</p></div></div></section>
  </div>;
}
