import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Search as SearchIcon } from "lucide-react";
import { supabase } from "../lib/supabase";
import { OpportunityCard } from "../components/OpportunityCard";
import type { Organization, OpportunityCategory } from "../types/database";

function useSearchOpportunities(term:string){return useQuery({queryKey:["search-opportunities",term],enabled:term.trim().length>1,queryFn:async()=>{const {data,error}=await supabase.from("opportunities").select("*, organizations(name, verified, is_sponsored), opportunity_categories(name, icon, color)").eq("status","active").textSearch("search_vector",term.trim().split(/\s+/).join(" & ")).limit(30);if(error)throw error;return data??[];}})}
export function SearchPage(){const [input,setInput]=useState("");const [term,setTerm]=useState("");const {data:results,isLoading,error}=useSearchOpportunities(term);return <div className="page-stack"><section><h1 className="text-2xl">Search</h1><p className="mt-1 text-ink-light">Search current opportunities by title, description or eligibility.</p></section><form onSubmit={e=>{e.preventDefault();setTerm(input)}} className="relative max-w-xl"><SearchIcon size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-ink-faint"/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Try scholarship, internship, developer…" className="w-full rounded-full border border-ink-faint/30 bg-white py-3 pl-11 pr-4 text-[15px] outline-none focus:border-brand"/></form><div>{term.trim().length<=1&&<p className="text-ink-light">Type at least two characters and press Enter.</p>}{isLoading&&<p className="text-ink-light">Searching…</p>}{error&&<p className="text-flag">Search failed — try a different term.</p>}{!isLoading&&!error&&term.trim().length>1&&results?.length===0&&<p className="text-ink-light">No opportunities matched “{term}”.</p>}{results?.map(opp=><OpportunityCard key={opp.id} opportunity={opp} organization={opp.organizations as Pick<Organization,"name"|"verified"|"is_sponsored">|null} category={opp.opportunity_categories as Pick<OpportunityCategory,"name"|"icon"|"color">|null}/>)}</div></div>}
