import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {CalendarPlus,Plus} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {useAuth} from '../store/auth';
import {useGroupAction} from '../hooks/useGroups';
import {searchFilter} from '../lib/search';
import {deadlineCalendar} from '../lib/nextStep';
import {usePersistentDraft} from '../hooks/usePersistentDraft';

type Listing={id:string;title:string;status:string;deadline:string|null;path:string;kind:'job'|'opportunity';location:string|null};
type Shared={id:string;shared_by:string;note:string;job_id:string|null;opportunity_id:string|null;job:{id:string;title:string;status:string;closes_at:string|null;location:string|null}|null;opportunity:{id:string;title:string;status:string;deadline:string|null;location:string|null}|null;profile:{full_name:string|null}|null};
const isOpen=(item:Listing)=>['open','active'].includes(item.status)&&(!item.deadline||Date.parse(item.deadline)>Date.now());
export function GroupOpportunities({groupId,managing}:{groupId:string;managing:boolean}){
 const {userId}=useAuth();const action=useGroupAction();const [input,setInput]=useState('');const [term,setTerm]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [note,setNote,clearNote]=usePersistentDraft(`group-opportunity-note:${userId}:${groupId}`,'');
 const query=useQuery({queryKey:['groups',userId,groupId,'opportunities'],queryFn:async()=>{const {data,error}=await supabase.from('community_opportunities').select('*, job:job_postings(id,title,status,closes_at,location), opportunity:opportunities(id,title,status,deadline,location), profile:profiles(full_name)').eq('group_id',groupId).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data as unknown as Shared[];}});
 const search=useQuery({queryKey:['share-opportunity-search',userId,term],enabled:term.length>=2,queryFn:async()=>{
  const now=new Date().toISOString();const [jobs,opportunities]=await Promise.all([supabase.from('job_postings').select('id,title,status,closes_at,location').eq('status','open').or(`closes_at.is.null,closes_at.gt.${now}`).or(searchFilter(['title','description'],term)).limit(15),supabase.from('opportunities').select('id,title,status,deadline,location').eq('status','active').or(`deadline.is.null,deadline.gt.${now}`).or(searchFilter(['title','description'],term)).limit(15)]);if(jobs.error)throw jobs.error;if(opportunities.error)throw opportunities.error;
  return [...jobs.data.map(j=>({...j,kind:'job' as const,deadline:j.closes_at,path:`/jobs/${j.id}`})),...opportunities.data.map(o=>({...o,kind:'opportunity' as const,path:`/opportunities/${o.id}`}))] as Listing[];
 }});
 async function share(item:Listing){setError('');setNotice('');try{await action.mutateAsync({action:'share_opportunity',gid:groupId,payload:{kind:item.kind,target_id:item.id,note}});clearNote();setTerm('');setInput('');setNotice('Shared with your group.');}catch(e){setError((e as Error).message);}}
 function calendar(item:Listing){try{const blob=new Blob([deadlineCalendar(item,location.origin)],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='possara-deadline.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setError((e as Error).message);}}
 const shared=(query.data??[]).map(row=>({row,item:row.job?{...row.job,deadline:row.job.closes_at,path:`/jobs/${row.job.id}`,kind:'job' as const}:row.opportunity?{...row.opportunity,path:`/opportunities/${row.opportunity.id}`,kind:'opportunity' as const}:null})).sort((a,b)=>Number(!!b.item&&isOpen(b.item))-Number(!!a.item&&isOpen(a.item))||(Date.parse(a.item?.deadline??'')||Infinity)-(Date.parse(b.item?.deadline??'')||Infinity));
 return <section className="space-y-4"><div className="rounded-2xl bg-brand-light/40 p-4"><h2 className="text-lg font-semibold">Possibilities worth sharing</h2><p className="mt-1 text-sm text-ink-light">Keep jobs, scholarships and other opportunities here, with the nearest deadlines first.</p>
  <form className="mt-3 flex gap-2" onSubmit={event=>{event.preventDefault();setTerm(input.trim());}}><input aria-label="Find an opportunity to share" placeholder="Search jobs or opportunities" className="min-w-0 flex-1 rounded-xl border bg-white p-3 text-sm" value={input} minLength={2} maxLength={120} required onChange={event=>setInput(event.target.value)}/><button className="rounded-xl bg-ink px-3 text-sm text-white">Find</button></form>
  {term&&<div className="mt-3 space-y-2"><label className="block text-xs font-medium">Add a note (optional)<textarea className="mt-1 w-full rounded-xl border p-3 text-sm" maxLength={1000} value={note} onChange={event=>setNote(event.target.value)} placeholder="Why might this help your group?"/></label>{search.isPending?<p role="status">Searching…</p>:search.error?<p role="alert">Could not load listings. <button className="underline" onClick={()=>search.refetch()}>Retry</button></p>:!search.data?.length?<p className="text-sm text-ink-light">No open listings matched.</p>:search.data.map(item=><div key={item.path} className="flex items-center gap-2 rounded-xl bg-white p-3"><Link to={item.path} className="min-w-0 flex-1 text-sm font-medium hover:underline">{item.title}<span className="block text-xs font-normal text-ink-light">{item.kind==='job'?'Job':'Opportunity'} · {item.location||'See listing'}</span></Link><button aria-label={`Share ${item.title}`} className="shrink-0 rounded-lg bg-brand-light p-2 text-brand-dark disabled:opacity-50" disabled={action.isPending} onClick={()=>share(item)}><Plus size={18}/></button></div>)}</div>}
 </div>
 {error&&<p role="alert" className="text-sm text-flag">{error}</p>}{notice&&<p role="status" className="text-sm text-brand-dark">{notice}</p>}
 {query.isPending?<p role="status">Loading shared opportunities…</p>:query.error?<p role="alert">Could not load shared opportunities. <button className="underline" onClick={()=>query.refetch()}>Retry</button></p>:!shared.length?<p className="rounded-2xl border border-dashed p-5 text-center text-sm text-ink-light">Share the first opportunity for your group.</p>:shared.map(({row,item})=><article key={row.id} className="rounded-2xl border bg-white p-4"><p className="text-xs font-medium text-brand-dark">{item&&isOpen(item)?'Open':'Closed or unavailable'}</p>{item?<Link to={item.path} className="mt-1 block break-words text-lg font-semibold hover:underline">{item.title}</Link>:<h3 className="mt-1 font-semibold">This listing is no longer available</h3>}{item?.deadline&&<p className="mt-1 text-sm text-ink-light">Deadline: {new Date(item.deadline).toLocaleString()}</p>}{row.note&&<p className="mt-2 whitespace-pre-wrap break-words text-sm">{row.note}</p>}<Link to={`/profile/id/${row.shared_by}`} className="mt-2 block text-xs text-ink-light hover:underline">Shared by {row.profile?.full_name||'Member'}</Link><div className="mt-3 flex flex-wrap gap-3">{item?.deadline&&isOpen(item)&&<button className="inline-flex items-center gap-1 text-xs font-medium text-brand-dark" onClick={()=>calendar(item)}><CalendarPlus size={14}/>Add deadline to calendar</button>}{(managing||row.shared_by===userId)&&<button disabled={action.isPending} className="text-xs text-ink-light" onClick={async()=>{if(!window.confirm('Remove this listing from the group?'))return;try{await action.mutateAsync({action:'remove_opportunity',gid:groupId,payload:{id:row.id}});}catch(e){setError((e as Error).message);}}}>Remove from group</button>}</div></article>)}
 </section>;
}
