-- POSSARA organization-owned hiring foundation.
alter table public.organizations add column if not exists handle text, add column if not exists verification_status text not null default 'unverified', add column if not exists category text, add column if not exists location text;
create unique index if not exists organizations_handle_unique on public.organizations(lower(handle)) where handle is not null;
alter table public.organizations drop constraint if exists organizations_verification_status_check;
alter table public.organizations add constraint organizations_verification_status_check check(verification_status in('unverified','pending','verified'));
update public.organizations set verification_status='verified' where coalesce(verified,false);

create table if not exists public.organization_members(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,role text not null default 'viewer' check(role in('owner','recruiter','viewer')),invited_at timestamptz not null default now(),joined_at timestamptz,unique(organization_id,user_id));
insert into public.organization_members(organization_id,user_id,role,joined_at) select id,owner_id,'owner',created_at from public.organizations where owner_id is not null on conflict(organization_id,user_id) do update set role='owner',joined_at=coalesce(public.organization_members.joined_at,excluded.joined_at);
create table if not exists public.job_postings(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,title text not null,role_type text not null,rank text not null check(rank in('Entry','Junior','Senior','Supervisor','Manager')),employment_type text not null check(employment_type in('Full-time','Part-time','Contract')),work_style text not null default 'On-site' check(work_style in('On-site','Hybrid','Remote')),location text not null,pay_min numeric,pay_max numeric,description text not null,requirements text[] not null default '{}',requires_cbt boolean not null default false,status text not null default 'draft' check(status in('draft','open','closed','filled')),posted_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),closes_at timestamptz);
create index if not exists job_postings_org_status_idx on public.job_postings(organization_id,status,created_at desc);
create table if not exists public.screening_questions(id uuid primary key default gen_random_uuid(),job_posting_id uuid not null references public.job_postings(id) on delete cascade,question_text text not null,answer_type text not null check(answer_type in('short_text','number','date','yes_no','single_choice')),choices jsonb,required boolean not null default true,sort_order int not null default 0);
create table if not exists public.interview_questions(id uuid primary key default gen_random_uuid(),job_posting_id uuid not null references public.job_postings(id) on delete cascade,question_text text not null,answer_type text not null check(answer_type in('short_text','number','date','yes_no','single_choice')),choices jsonb,sort_order int not null default 0);
create table if not exists public.job_applications(id uuid primary key default gen_random_uuid(),job_posting_id uuid not null references public.job_postings(id) on delete cascade,applicant_id uuid not null references public.profiles(id) on delete cascade,cv_url text not null,cover_letter_text text,cover_letter_url text,photo_url text,status text not null default 'new' check(status in('new','shortlisted','rejected','hired','withdrawn')),match_score int check(match_score between 0 and 100),applied_at timestamptz not null default now(),unique(job_posting_id,applicant_id));
create table if not exists public.job_question_answers(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.job_applications(id) on delete cascade,question_id uuid not null,question_kind text not null check(question_kind in('screening','interview')),answer_value text not null,unique(application_id,question_id,question_kind));
create table if not exists public.job_cbt_questions(id uuid primary key default gen_random_uuid(),job_posting_id uuid not null references public.job_postings(id) on delete cascade,question_text text not null,choices jsonb not null,correct_choice text not null,sort_order int not null default 0);
create table if not exists public.job_cbt_attempts(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.job_applications(id) on delete cascade,started_at timestamptz not null default now(),submitted_at timestamptz,score int,time_limit_seconds int not null default 900,unique(application_id));
create table if not exists public.job_cbt_answers(id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.job_cbt_attempts(id) on delete cascade,question_id uuid not null references public.job_cbt_questions(id) on delete cascade,selected_choice text not null,unique(attempt_id,question_id));

alter table public.organization_members enable row level security; alter table public.job_postings enable row level security; alter table public.screening_questions enable row level security; alter table public.interview_questions enable row level security; alter table public.job_applications enable row level security; alter table public.job_question_answers enable row level security; alter table public.job_cbt_questions enable row level security; alter table public.job_cbt_attempts enable row level security; alter table public.job_cbt_answers enable row level security;

drop policy if exists "Members can view own memberships" on public.organization_members; create policy "Members can view own memberships" on public.organization_members for select to authenticated using((select auth.uid())=user_id);
drop policy if exists "Owners manage organization members" on public.organization_members; create policy "Owners manage organization members" on public.organization_members for all to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.organizations o where o.id=organization_id and o.owner_id=(select auth.uid()))) with check(exists(select 1 from public.organizations o where o.id=organization_id and o.owner_id=(select auth.uid())));
drop policy if exists "Open jobs are public" on public.job_postings; create policy "Open jobs are public" on public.job_postings for select to anon,authenticated using(status='open' or exists(select 1 from public.organization_members om where om.organization_id=job_postings.organization_id and om.user_id=(select auth.uid())));
drop policy if exists "Recruiters manage jobs" on public.job_postings; create policy "Recruiters manage jobs" on public.job_postings for all to authenticated using(exists(select 1 from public.organization_members om where om.organization_id=job_postings.organization_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter'))) with check(posted_by=(select auth.uid()) and exists(select 1 from public.organization_members om where om.organization_id=job_postings.organization_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter')));
drop policy if exists "Public reads screening for open jobs" on public.screening_questions; create policy "Public reads screening for open jobs" on public.screening_questions for select to anon,authenticated using(exists(select 1 from public.job_postings j where j.id=job_posting_id and j.status='open'));
drop policy if exists "Recruiters manage screening" on public.screening_questions; create policy "Recruiters manage screening" on public.screening_questions for all to authenticated using(exists(select 1 from public.job_postings j join public.organization_members om on om.organization_id=j.organization_id where j.id=job_posting_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter'))) with check(exists(select 1 from public.job_postings j join public.organization_members om on om.organization_id=j.organization_id where j.id=job_posting_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter')));
drop policy if exists "Applicants create applications" on public.job_applications; create policy "Applicants create applications" on public.job_applications for insert to authenticated with check((select auth.uid())=applicant_id and status='new' and exists(select 1 from public.job_postings j where j.id=job_posting_id and j.status='open'));
drop policy if exists "Applicants and recruiters view applications" on public.job_applications; create policy "Applicants and recruiters view applications" on public.job_applications for select to authenticated using((select auth.uid())=applicant_id or exists(select 1 from public.job_postings j join public.organization_members om on om.organization_id=j.organization_id where j.id=job_posting_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter')));
drop policy if exists "Recruiters update applications" on public.job_applications; create policy "Recruiters update applications" on public.job_applications for update to authenticated using(exists(select 1 from public.job_postings j join public.organization_members om on om.organization_id=j.organization_id where j.id=job_posting_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter'))) with check(exists(select 1 from public.job_postings j join public.organization_members om on om.organization_id=j.organization_id where j.id=job_posting_id and om.user_id=(select auth.uid()) and om.role in('owner','recruiter')));
drop policy if exists "Application participants read answers" on public.job_question_answers; create policy "Application participants read answers" on public.job_question_answers for select to authenticated using(exists(select 1 from public.job_applications a left join public.job_postings j on j.id=a.job_posting_id left join public.organization_members om on om.organization_id=j.organization_id and om.user_id=(select auth.uid()) where a.id=application_id and(a.applicant_id=(select auth.uid()) or om.role in('owner','recruiter'))));
drop policy if exists "Applicants answer own questions" on public.job_question_answers; create policy "Applicants answer own questions" on public.job_question_answers for insert to authenticated with check(exists(select 1 from public.job_applications a where a.id=application_id and a.applicant_id=(select auth.uid())));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('job-documents','job-documents',false,5242880,array['application/pdf']) on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['application/pdf'];
drop policy if exists "Applicants upload own job documents" on storage.objects; create policy "Applicants upload own job documents" on storage.objects for insert to authenticated with check(bucket_id='job-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Applicants read own job documents" on storage.objects; create policy "Applicants read own job documents" on storage.objects for select to authenticated using(bucket_id='job-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Applicants update own job documents" on storage.objects; create policy "Applicants update own job documents" on storage.objects for update to authenticated using(bucket_id='job-documents' and(storage.foldername(name))[1]=(select auth.uid())::text) with check(bucket_id='job-documents' and(storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Recruiters read applicant job documents" on storage.objects; create policy "Recruiters read applicant job documents" on storage.objects for select to authenticated using(bucket_id='job-documents' and exists(select 1 from public.job_applications a join public.job_postings j on j.id=a.job_posting_id join public.organization_members om on om.organization_id=j.organization_id where a.cv_url=name and om.user_id=(select auth.uid()) and om.role in('owner','recruiter')));

grant select on public.organization_members,public.job_postings,public.screening_questions,public.interview_questions,public.job_applications,public.job_question_answers,public.job_cbt_questions,public.job_cbt_attempts,public.job_cbt_answers to authenticated;
grant insert,update,delete on public.organization_members,public.job_postings,public.screening_questions,public.interview_questions,public.job_applications,public.job_question_answers,public.job_cbt_questions,public.job_cbt_attempts,public.job_cbt_answers to authenticated;
grant select on public.job_postings,public.screening_questions to anon;
