-- Lock CBT attempts to one server-timed submission.
drop policy if exists "Applicants manage own CBT attempt" on public.job_cbt_attempts;
create policy "Applicants read own CBT attempt" on public.job_cbt_attempts for select to authenticated using(exists(select 1 from public.job_applications a where a.id=application_id and a.applicant_id=auth.uid()));
drop policy if exists "Applicants manage own CBT answers" on public.job_cbt_answers;
create policy "Applicants read own CBT answers" on public.job_cbt_answers for select to authenticated using(exists(select 1 from public.job_cbt_attempts t join public.job_applications a on a.id=t.application_id where t.id=attempt_id and a.applicant_id=auth.uid()));
drop policy if exists "Recruiters read CBT answers" on public.job_cbt_answers;
create policy "Recruiters read CBT answers" on public.job_cbt_answers for select to authenticated using(exists(select 1 from public.job_cbt_attempts t join public.job_applications a on a.id=t.application_id join public.job_postings j on j.id=a.job_posting_id join public.organization_members om on om.organization_id=j.organization_id where t.id=attempt_id and om.user_id=auth.uid() and om.role in('owner','recruiter')));
create or replace function public.start_job_cbt(p_application_id uuid) returns table(started_at timestamptz,time_limit_seconds integer) language plpgsql security definer set search_path=public as $$ declare v_job uuid; v_attempt public.job_cbt_attempts%rowtype; begin select job_posting_id into v_job from public.job_applications where id=p_application_id and applicant_id=auth.uid(); if v_job is null then raise exception 'Application not found'; end if; if not exists(select 1 from public.job_postings where id=v_job and requires_cbt=true) then raise exception 'CBT is not required for this role'; end if; if not exists(select 1 from public.job_cbt_questions where job_posting_id=v_job) then raise exception 'Assessment is not ready'; end if; select * into v_attempt from public.job_cbt_attempts where application_id=p_application_id; if v_attempt.submitted_at is not null then raise exception 'Assessment has already been submitted'; end if; if v_attempt.id is null then insert into public.job_cbt_attempts(application_id,started_at,time_limit_seconds) values(p_application_id,now(),900) returning * into v_attempt; end if; return query select v_attempt.started_at,coalesce(v_attempt.time_limit_seconds,900); end $$;
create or replace function public.submit_job_cbt(p_application_id uuid,p_answers jsonb) returns integer language plpgsql security definer set search_path=public as $$ declare v_job uuid; v_total int; v_correct int; v_score int; v_attempt public.job_cbt_attempts%rowtype; begin select job_posting_id into v_job from public.job_applications where id=p_application_id and applicant_id=auth.uid(); if v_job is null then raise exception 'Application not found'; end if; select * into v_attempt from public.job_cbt_attempts where application_id=p_application_id for update; if v_attempt.id is null then raise exception 'Assessment has not been started'; end if; if v_attempt.submitted_at is not null then raise exception 'Assessment has already been submitted'; end if; if now()>v_attempt.started_at+make_interval(secs=>coalesce(v_attempt.time_limit_seconds,900)+30) then raise exception 'Assessment time has elapsed'; end if; select count(*),count(*) filter(where p_answers->>q.id::text=q.correct_choice) into v_total,v_correct from public.job_cbt_questions q where q.job_posting_id=v_job; if v_total=0 then raise exception 'Assessment has no questions'; end if; v_score:=round((v_correct::numeric/v_total::numeric)*100); update public.job_cbt_attempts set submitted_at=now(),score=v_score where id=v_attempt.id; insert into public.job_cbt_answers(attempt_id,question_id,selected_choice) select v_attempt.id,q.id,p_answers->>q.id::text from public.job_cbt_questions q where q.job_posting_id=v_job and p_answers ? q.id::text; return v_score; end $$;
revoke all on function public.start_job_cbt(uuid) from public,anon; grant execute on function public.start_job_cbt(uuid) to authenticated;
revoke all on function public.submit_job_cbt(uuid,jsonb) from public,anon; grant execute on function public.submit_job_cbt(uuid,jsonb) to authenticated;
revoke all on function public.get_job_cbt_questions(uuid) from public,anon; grant execute on function public.get_job_cbt_questions(uuid) to authenticated;
